create table part0 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

create table part1 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

create table part2 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

create table part3 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

insert into part1 (value, gender) values ('tororó', 2);
insert into part1 (value, gender) values ('manequim', 0);
insert into part1 (value, gender) values ('pikachu', 0);
insert into part1 (value, gender) values ('filhote tartaruga', 0);

insert into part1 (value, gender) values ('bola', 1);
insert into part1 (value, gender) values ('mula', 1);
insert into part1 (value, gender) values ('égua', 1);
insert into part1 (value, gender) values ('girafa', 1);
insert into part1 (value, gender) values ('pamonha', 1);
insert into part1 (value, gender) values ('múmia', 1);
insert into part1 (value, gender) values ('cadeira', 1);
insert into part1 (value, gender) values ('ratazana', 1);
insert into part1 (value, gender) values ('barata', 1);
insert into part1 (value, gender) values ('batata', 1);
insert into part1 (value, gender) values ('lua', 1);
insert into part1 (value, gender) values ('meia', 1);
insert into part1 (value, gender) values ('vespa', 1);
insert into part1 (value, gender) values ('cobra', 1);
insert into part1 (value, gender) values ('pokébola', 1);
insert into part1 (value, gender) values ('anta', 1);
insert into part1 (value, gender) values ('ova de magikarp', 1);
insert into part1 (value, gender) values ('pedra', 1);
insert into part1 (value, gender) values ('tartaruga ninja', 1);
insert into part1 (value, gender) values ('pipa', 1);
insert into part1 (value, gender) values ('bananinha', 1);
insert into part1 (value, gender) values ('banana', 1);
insert into part1 (value, gender) values ('galinha pintadinha', 1);
insert into part1 (value, gender) values ('sereia fora dágua', 1);
insert into part1 (value, gender) values ('paçoca', 1);
insert into part1 (value, gender) values ('fruto de gambiarra', 1);
insert into part1 (value, gender) values ('fruto do mar', 2);
insert into part1 (value, gender) values ('ser marítimo', 2);
insert into part1 (value, gender) values ('cavalo marinho', 2);
insert into part1 (value, gender) values ('pinguim', 0);
insert into part1 (value, gender) values ('pipoqueira', 1);
insert into part1 (value, gender) values ('pipoqueiro', 1);
insert into part1 (value, gender) values ('bêbada', 1);
insert into part1 (value, gender) values ('bêbado', 2);
insert into part1 (value, gender) values ('queimada', 1);
insert into part1 (value, gender) values ('queimado', 2);

insert into part1 (value, gender) values ('esqueleto', 2);
insert into part1 (value, gender) values ('picolé', 2);
insert into part1 (value, gender) values ('cone', 2);
insert into part1 (value, gender) values ('ornitorrinco', 2);
insert into part1 (value, gender) values ('porco espinho', 2);
insert into part1 (value, gender) values ('pickles', 2);
insert into part1 (value, gender) values ('diabo', 2);
insert into part1 (value, gender) values ('peixe', 2);
insert into part1 (value, gender) values ('enfeite de oferenda', 2);
insert into part1 (value, gender) values ('enfeite de presente', 2);
insert into part1 (value, gender) values ('enfeite de arroz', 2);
insert into part1 (value, gender) values ('defunto', 2);
insert into part1 (value, gender) values ('filhote de rato', 2);
insert into part1 (value, gender) values ('pokémon', 2);

-- part 2
insert into part2 (value, gender) values ('de bolinhas', 0);
insert into part2 (value, gender) values ('bugada', 1);
insert into part2 (value, gender) values ('bugado', 2);
insert into part2 (value, gender) values ('manco', 2);
insert into part2 (value, gender) values ('manca', 1);
insert into part2 (value, gender) values ('molhado', 2);
insert into part2 (value, gender) values ('molhada', 1);
insert into part2 (value, gender) values ('prematura', 1);
insert into part2 (value, gender) values ('prematuro', 2);
insert into part2 (value, gender) values ('hipnotizada', 1);
insert into part2 (value, gender) values ('hipnotizado', 2);
insert into part2 (value, gender) values ('mole', 0);
insert into part2 (value, gender) values ('de agulha', 0);
insert into part2 (value, gender) values ('molenga', 0);
insert into part2 (value, gender) values ('ambulante', 0);
insert into part2 (value, gender) values ('azul', 0);
insert into part2 (value, gender) values ('quadrada', 1);
insert into part2 (value, gender) values ('quadrado', 2);
insert into part2 (value, gender) values ('senoidal', 0);
insert into part2 (value, gender) values ('quebrada', 1);
insert into part2 (value, gender) values ('quebrado', 2);
insert into part2 (value, gender) values ('de jiló', 0);
insert into part2 (value, gender) values ('cara de mamão', 0);
insert into part2 (value, gender) values ('careca', 0);
insert into part2 (value, gender) values ('de rodinhas', 0);
insert into part2 (value, gender) values ('intragável', 0);
insert into part2 (value, gender) values ('bolha', 0);
insert into part2 (value, gender) values ('mal', 0);
insert into part2 (value, gender) values ('sem bago', 0);
insert into part2 (value, gender) values ('ululante', 0);
insert into part2 (value, gender) values ('furada', 1);
insert into part2 (value, gender) values ('furado', 2);
insert into part2 (value, gender) values ('marrom', 0);
insert into part2 (value, gender) values ('amassada', 1);
insert into part2 (value, gender) values ('amassado', 2);
insert into part2 (value, gender) values ('minguante', 0);
insert into part2 (value, gender) values ('cheia', 1);
insert into part2 (value, gender) values ('cheio', 2);
insert into part2 (value, gender) values ('elétrica', 1);
insert into part2 (value, gender) values ('elétrico', 2);
insert into part2 (value, gender) values ('sem rodinhas', 0);
insert into part2 (value, gender) values ('enferrujada', 1);
insert into part2 (value, gender) values ('enferrujado', 2);
insert into part2 (value, gender) values ('amarrada', 1);
insert into part2 (value, gender) values ('amarrado', 2);
insert into part2 (value, gender) values ('esverdeada', 1);
insert into part2 (value, gender) values ('esverdeado', 2);
insert into part2 (value, gender) values ('com gosto de salsicha', 0);
insert into part2 (value, gender) values ('animal', 0);
insert into part2 (value, gender) values ('do cabelo pixaim', 0);
insert into part2 (value, gender) values ('sem cabelo', 0);
insert into part2 (value, gender) values ('da montanha', 0);
insert into part2 (value, gender) values ('sem mochila', 0);
insert into part2 (value, gender) values ('suja', 1);
insert into part2 (value, gender) values ('sujo', 2);
insert into part2 (value, gender) values ('amarga', 1);
insert into part2 (value, gender) values ('amargo', 2);
insert into part2 (value, gender) values ('uvinha de mulher', 0);
insert into part2 (value, gender) values ('minecrafter', 0);
insert into part2 (value, gender) values ('de óculos', 0);
insert into part2 (value, gender) values ('sem óculos', 0);
insert into part2 (value, gender) values ('sem nariz', 0);
insert into part2 (value, gender) values ('sem maquiagem', 0);
insert into part2 (value, gender) values ('perdida', 1);
insert into part2 (value, gender) values ('perdido', 2);
insert into part2 (value, gender) values ('pif pif', 0);
insert into part2 (value, gender) values ('sem dedo', 0);
insert into part2 (value, gender) values ('cigana', 1);
insert into part2 (value, gender) values ('cigano', 2);

-- part 3
insert into part3 (value, gender) values ('amarela', 1);
insert into part3 (value, gender) values ('amarelo', 2);
insert into part3 (value, gender) values ('de taubaté', 0);
insert into part3 (value, gender) values ('bola bola', 0);
insert into part3 (value, gender) values ('gelada', 1);
insert into part3 (value, gender) values ('gelado', 2);
insert into part3 (value, gender) values ('sem dente', 0);
insert into part3 (value, gender) values ('vendedora de produtos jequiti', 1);
insert into part3 (value, gender) values ('vendedor da jequiti', 2);
insert into part3 (value, gender) values ('vendedora da avon', 1);
insert into part3 (value, gender) values ('vendedor da avon', 2);
insert into part3 (value, gender) values ('de raio laser', 0);
insert into part3 (value, gender) values ('mobile', 0);
insert into part3 (value, gender) values ('na noite', 0);
insert into part3 (value, gender) values ('noturna', 1);
insert into part3 (value, gender) values ('noturno', 2);
insert into part3 (value, gender) values ('parecida com o sonic', 1);
insert into part3 (value, gender) values ('parecido com o sonic', 2);
insert into part3 (value, gender) values ('de skate', 0);
insert into part3 (value, gender) values ('vermelha', 1);
insert into part3 (value, gender) values ('vermelho', 2);
insert into part3 (value, gender) values ('madura', 1);
insert into part3 (value, gender) values ('maduro', 2);
insert into part3 (value, gender) values ('sem mãe', 0);
insert into part3 (value, gender) values ('sem pau', 0);
insert into part3 (value, gender) values ('do pau', 0);
insert into part3 (value, gender) values ('incubada', 1);
insert into part3 (value, gender) values ('incubado', 2);
insert into part3 (value, gender) values ('no insulfilme', 0);
insert into part3 (value, gender) values ('vegana', 1);
insert into part3 (value, gender) values ('vegano', 2);
insert into part3 (value, gender) values ('vegetal', 0);
insert into part3 (value, gender) values ('com tomate seco', 0);
insert into part3 (value, gender) values ('parecida com a medusa', 1);
insert into part3 (value, gender) values ('parecido com a medusa', 2);
insert into part3 (value, gender) values ('perfurante', 0);
insert into part3 (value, gender) values ('voadora', 1);
insert into part3 (value, gender) values ('voador', 2);
insert into part3 (value, gender) values ('filhote de peppa pig', 0);
insert into part3 (value, gender) values ('jogadora de lol', 1);
insert into part3 (value, gender) values ('jogador de lol', 2);
insert into part3 (value, gender) values ('jogadora de minecraft', 1);
insert into part3 (value, gender) values ('jogador de minecraft', 2);
insert into part3 (value, gender) values ('no caixão', 0);
insert into part3 (value, gender) values ('sem caixão', 0);
insert into part3 (value, gender) values ('conservada', 1);
insert into part3 (value, gender) values ('conservado', 2);
insert into part3 (value, gender) values ('acabada', 1);
insert into part3 (value, gender) values ('acabado', 2);
insert into part3 (value, gender) values ('na superfície', 0);
insert into part3 (value, gender) values ('enterrada', 1);
insert into part3 (value, gender) values ('enterrado', 2);
insert into part3 (value, gender) values ('descascada', 1);
insert into part3 (value, gender) values ('descascado', 2);
insert into part3 (value, gender) values ('desencapada', 1);
insert into part3 (value, gender) values ('desencapado', 2);
insert into part3 (value, gender) values ('desenrolada', 1);
insert into part3 (value, gender) values ('desenrolado', 2);
insert into part3 (value, gender) values ('farpada', 1);
insert into part3 (value, gender) values ('farpado', 2);
insert into part3 (value, gender) values ('descalibrada', 1);
insert into part3 (value, gender) values ('descalibrado', 2);
insert into part3 (value, gender) values ('vazia', 1);
insert into part3 (value, gender) values ('vazio', 2);
insert into part3 (value, gender) values ('mal passada', 1);
insert into part3 (value, gender) values ('mal passado', 2);
insert into part3 (value, gender) values ('inacabada', 1);
insert into part3 (value, gender) values ('inacabado', 2);
insert into part3 (value, gender) values ('torta', 1);
insert into part3 (value, gender) values ('torto', 2);
insert into part3 (value, gender) values ('estraviado pelos correios', 2);
insert into part3 (value, gender) values ('viajante', 0);
insert into part3 (value, gender) values ('congelada', 1);
insert into part3 (value, gender) values ('congelado', 2);
insert into part3 (value, gender) values ('desnutrida', 1);
insert into part3 (value, gender) values ('desnutrido', 2);
insert into part3 (value, gender) values ('polar', 0);
insert into part3 (value, gender) values ('mecânica', 1);
insert into part3 (value, gender) values ('mecânico', 2);
insert into part3 (value, gender) values ('desacoplada', 1);
insert into part3 (value, gender) values ('desacoplado', 2);
insert into part3 (value, gender) values ('marinha', 1);
insert into part3 (value, gender) values ('marinho', 2);
insert into part3 (value, gender) values ('terrestre', 0);
insert into part3 (value, gender) values ('aérea', 1);
insert into part3 (value, gender) values ('aéreo', 2);
insert into part3 (value, gender) values ('na autópsia', 0);
insert into part3 (value, gender) values ('da era feudal', 0);
insert into part3 (value, gender) values ('em 240p', 0);
insert into part3 (value, gender) values ('com gergelim', 0);
insert into part3 (value, gender) values ('meio amarga', 1);
insert into part3 (value, gender) values ('meio amargo', 2);
insert into part3 (value, gender) values ('parecida com o pikachu', 1);
insert into part3 (value, gender) values ('parecido com o pikachu', 2);
insert into part3 (value, gender) values ('deslizante', 0);

-- 2021-02-08
update part1 set value = 'ova de magikarp' where value = 'sua magikarp';
update part1 set value = 'manequim', gender = 0 where value = 'seu manequim';
update part1 set value = 'pikachu', gender = 0 where value = 'seu pikachu';
update part1 set value = 'filhote de tartaruga', gender = 0 where value = 'sua tartaruga';

insert into part1 (value, gender) values ('quimera', 0);
insert into part1 (value, gender) values ('batata canoa', 1);
insert into part1 (value, gender) values ('baka', 0);
insert into part1 (value, gender) values ('salgadinho', 2);
insert into part1 (value, gender) values ('ameba', 1);
insert into part1 (value, gender) values ('marisco', 2);
insert into part1 (value, gender) values ('traveca', 1);
insert into part1 (value, gender) values ('traveco', 2);
insert into part1 (value, gender) values ('uvinha', 1);
insert into part1 (value, gender) values ('pau', 2);
insert into part1 (value, gender) values ('toalha', 1);
insert into part1 (value, gender) values ('pagodeira', 1);
insert into part1 (value, gender) values ('pagodeiro', 2);
insert into part1 (value, gender) values ('piano desafinado', 2);
insert into part1 (value, gender) values ('participante do big brother', 0);
insert into part1 (value, gender) values ('bagre', 2);
insert into part1 (value, gender) values ('artista', 0);
insert into part1 (value, gender) values ('dízima periódica', 1);
insert into part1 (value, gender) values ('zero à esquerda', 2);
insert into part1 (value, gender) values ('formiga', 1);
insert into part1 (value, gender) values ('falta de sacanagem', 1);
insert into part1 (value, gender) values ('patê', 2);
insert into part1 (value, gender) values ('fatality', 2);
insert into part1 (value, gender) values ('letreiro', 2);
insert into part1 (value, gender) values ('boneco assassino', 2);
insert into part1 (value, gender) values ('besta', 1);
insert into part1 (value, gender) values ('giromba', 1);
insert into part1 (value, gender) values ('desgraça', 1);
insert into part1 (value, gender) values ('bosta', 1);
insert into part1 (value, gender) values ('vida', 1);
insert into part1 (value, gender) values ('t-rex', 2);
insert into part1 (value, gender) values ('pterodáctilo', 2);
insert into part1 (value, gender) values ('espécie em extinção', 1);

insert into part2 (value, gender) values ('parecido com o jason', 2);
insert into part2 (value, gender) values ('luminosa', 1);
insert into part2 (value, gender) values ('luminoso', 2);
insert into part2 (value, gender) values ('refutada', 1);
insert into part2 (value, gender) values ('refutado', 2);
insert into part2 (value, gender) values ('globalista', 0);
insert into part2 (value, gender) values ('terraplanista', 0);
insert into part2 (value, gender) values ('sem vírgula', 0);
insert into part2 (value, gender) values ('desmilinguida', 1);
insert into part2 (value, gender) values ('desmilinguido', 2);
insert into part2 (value, gender) values ('dissolvida', 1);
insert into part2 (value, gender) values ('dissolvido', 2);
insert into part2 (value, gender) values ('safada', 1);
insert into part2 (value, gender) values ('safado', 2);
insert into part2 (value, gender) values ('esfacelada', 1);
insert into part2 (value, gender) values ('esfacelado', 2);
insert into part2 (value, gender) values ('sem sal', 0);
insert into part2 (value, gender) values ('espongiforme', 0);
insert into part2 (value, gender) values ('estranha', 1);
insert into part2 (value, gender) values ('estranho', 2);
insert into part2 (value, gender) values ('cabeluda', 1);
insert into part2 (value, gender) values ('cabeludo', 2);
insert into part2 (value, gender) values ('de salto alto', 0);
insert into part2 (value, gender) values ('travestida de barbie', 1);
insert into part2 (value, gender) values ('travestido de urso', 2);
insert into part2 (value, gender) values ('dura', 1);
insert into part2 (value, gender) values ('duro', 2);
insert into part2 (value, gender) values ('mal feita', 1);
insert into part2 (value, gender) values ('mal feito', 2);
insert into part2 (value, gender) values ('panificada', 1);
insert into part2 (value, gender) values ('panificado', 2);
insert into part2 (value, gender) values ('ensaboada', 1);
insert into part2 (value, gender) values ('ensaboado', 2);
insert into part2 (value, gender) values ('barroca', 1);
insert into part2 (value, gender) values ('barroco', 2);
insert into part2 (value, gender) values ('assombrada', 1);
insert into part2 (value, gender) values ('assombrado', 2);
insert into part2 (value, gender) values ('surfista', 0);
insert into part2 (value, gender) values ('programador de php', 2);
insert into part2 (value, gender) values ('programadora de php', 2);
insert into part2 (value, gender) values ('desajustada', 1);
insert into part2 (value, gender) values ('desajustado', 2);
insert into part2 (value, gender) values ('saltitante', 0);
insert into part2 (value, gender) values ('grávida', 1);
insert into part2 (value, gender) values ('grávido', 2);
insert into part2 (value, gender) values ('de abobrinha', 0);
insert into part2 (value, gender) values ('de chuchu', 0);
insert into part2 (value, gender) values ('desqualificada', 1);
insert into part2 (value, gender) values ('desqualificado', 2);
insert into part2 (value, gender) values ('tarada', 1);
insert into part2 (value, gender) values ('tarado', 2);
insert into part2 (value, gender) values ('engasgada', 1);
insert into part2 (value, gender) values ('engasgado', 2);
insert into part2 (value, gender) values ('pole dancer', 0);
insert into part2 (value, gender) values ('desnorteada', 1);
insert into part2 (value, gender) values ('desnorteado', 2);
insert into part2 (value, gender) values ('passeando de crocs', 0);
insert into part2 (value, gender) values ('que desfila de crocs', 0);
insert into part2 (value, gender) values ('desfilando', 0);
insert into part2 (value, gender) values ('profunda', 1);
insert into part2 (value, gender) values ('profundo', 2);
insert into part2 (value, gender) values ('veiuda', 1);
insert into part2 (value, gender) values ('veiudo', 2);
insert into part2 (value, gender) values ('velha', 1);
insert into part2 (value, gender) values ('velho', 2);
insert into part2 (value, gender) values ('com gosto de peixe', 0);
insert into part2 (value, gender) values ('envelhecida', 1);
insert into part2 (value, gender) values ('envelhecido', 2);
insert into part2 (value, gender) values ('cachaceira', 1);
insert into part2 (value, gender) values ('cachaceiro', 2);
insert into part2 (value, gender) values ('bombada', 1);
insert into part2 (value, gender) values ('bombado', 2);
insert into part2 (value, gender) values ('de nadadeiras', 0);
insert into part2 (value, gender) values ('antagonista', 0);
insert into part2 (value, gender) values ('maníaca', 1);
insert into part2 (value, gender) values ('maníaco', 2);
insert into part2 (value, gender) values ('sedentária', 1);
insert into part2 (value, gender) values ('sedentário', 2);
insert into part2 (value, gender) values ('absolutamente', 0);
insert into part2 (value, gender) values ('oriunda do mar', 1);
insert into part2 (value, gender) values ('vindo do mar', 2);
insert into part2 (value, gender) values ('palpiteira', 1);
insert into part2 (value, gender) values ('palpiteiro', 2);
insert into part2 (value, gender) values ('ensanguentada', 1);
insert into part2 (value, gender) values ('ensanguentado', 2);
insert into part2 (value, gender) values ('maluca', 1);
insert into part2 (value, gender) values ('maluco', 2);
insert into part2 (value, gender) values ('com chapéu de alumínio', 0);
insert into part2 (value, gender) values ('folclórica', 1);
insert into part2 (value, gender) values ('folclórico', 2);
insert into part2 (value, gender) values ('alegórica', 1);
insert into part2 (value, gender) values ('alegórico', 2);
insert into part2 (value, gender) values ('hipocondríaca', 1);
insert into part2 (value, gender) values ('hipocondríaco', 2);
insert into part2 (value, gender) values ('figurante', 0);
insert into part2 (value, gender) values ('terrorista', 0);

insert into part3 (value, gender) values ('da calça quadrada', 0);
insert into part3 (value, gender) values ('parecendo uma amoeba', 0);
insert into part3 (value, gender) values ('amolecida', 1);
insert into part3 (value, gender) values ('amolecido', 2);
insert into part3 (value, gender) values ('global', 0);
insert into part3 (value, gender) values ('no ácido sulfúrico', 0);
insert into part3 (value, gender) values ('suspensa no ar', 1);
insert into part3 (value, gender) values ('suspenso no ar', 2);
insert into part3 (value, gender) values ('mastigada por um urso', 1);
insert into part3 (value, gender) values ('mastigado por uma ursinha', 2);
insert into part3 (value, gender) values ('pifada', 1);
insert into part3 (value, gender) values ('pifado', 2);
insert into part3 (value, gender) values ('sem tempero', 0);
insert into part3 (value, gender) values ('destemperada', 1);
insert into part3 (value, gender) values ('destemperado', 2);
insert into part3 (value, gender) values ('descabelada', 1);
insert into part3 (value, gender) values ('descabelado', 2);
insert into part3 (value, gender) values ('e malformada', 1);
insert into part3 (value, gender) values ('e malformado', 2);
insert into part3 (value, gender) values ('mal criada', 1);
insert into part3 (value, gender) values ('mal criado', 2);
insert into part3 (value, gender) values ('com cara de acidente de trem', 0);
insert into part3 (value, gender) values ('que parece a samara', 0);
insert into part3 (value, gender) values ('cancelada pela globo', 1);
insert into part3 (value, gender) values ('cancelado pelo sbt', 2);
insert into part3 (value, gender) values ('tendendo ao infinito', 0);
insert into part3 (value, gender) values ('da casca assombrosa', 1);
insert into part3 (value, gender) values ('do casco assombroso', 2);
insert into part3 (value, gender) values ('sem casaco', 0);
insert into part3 (value, gender) values ('com cara de silverfish', 0);
insert into part3 (value, gender) values ('sem bunda', 0);
insert into part3 (value, gender) values ('no mastro', 0);
insert into part3 (value, gender) values ('num objeto fálico', 0);
insert into part3 (value, gender) values ('sem calcinha', 0);
insert into part3 (value, gender) values ('de calcinha', 0);
insert into part3 (value, gender) values ('que xinga muito no twitter', 0);
insert into part3 (value, gender) values ('no desfiladeiro', 0);
insert into part3 (value, gender) values ('na beira do abismo', 0);
insert into part3 (value, gender) values ('da beira do abismo', 0);
insert into part3 (value, gender) values ('no penhasco', 0);
insert into part3 (value, gender) values ('mucha', 1);
insert into part3 (value, gender) values ('mucho', 2);
insert into part3 (value, gender) values ('podre', 0);
insert into part3 (value, gender) values ('fedida', 1);
insert into part3 (value, gender) values ('fedido', 2);
insert into part3 (value, gender) values ('no carvalho', 0);
insert into part3 (value, gender) values ('no barril', 0);
insert into part3 (value, gender) values ('apreciadora de paratudo', 1);
insert into part3 (value, gender) values ('degustador de paratudo', 2);
insert into part3 (value, gender) values ('sem cérebro', 0);
insert into part3 (value, gender) values ('acéfala', 1);
insert into part3 (value, gender) values ('acéfalo', 2);
insert into part3 (value, gender) values ('no lixo', 0);
insert into part3 (value, gender) values ('onomatopeica', 1);
insert into part3 (value, gender) values ('onomatopeico', 2);
insert into part3 (value, gender) values ('deserdada pela rainha', 1);
insert into part3 (value, gender) values ('deserdado pela rainha', 2);
insert into part3 (value, gender) values ('pra cacete', 0);
insert into part3 (value, gender) values ('para um caralho', 0);
insert into part3 (value, gender) values ('num navio cargueiro', 0);
insert into part3 (value, gender) values ('desfigurada', 1);
insert into part3 (value, gender) values ('desfigurado', 2);
insert into part3 (value, gender) values ('numa sexta feira 13', 0);
insert into part3 (value, gender) values ('esmagada por um titã anômalo', 1);
insert into part3 (value, gender) values ('esmagado por um titã bestial', 2);
insert into part3 (value, gender) values ('que parece que já morreu', 0);
insert into part3 (value, gender) values ('fingindo de morta', 1);
insert into part3 (value, gender) values ('com cara de morto', 2);
insert into part3 (value, gender) values ('conspiracionista', 0);
insert into part3 (value, gender) values ('de perna aberta', 0);
insert into part3 (value, gender) values ('sem perna', 0);
insert into part3 (value, gender) values ('em cima do muro', 0);
insert into part3 (value, gender) values ('da novela das 8', 0);
insert into part3 (value, gender) values ('de novela mexicana', 0);
insert into part3 (value, gender) values ('de dorama coreano', 0);
insert into part3 (value, gender) values ('depois da explosão', 0);
insert into part3 (value, gender) values ('do braço curto', 0);
insert into part3 (value, gender) values ('louca de pó', 1);
insert into part3 (value, gender) values ('virado no pó', 2);
insert into part3 (value, gender) values ('maconheira', 1);
insert into part3 (value, gender) values ('maconheiro', 2);

-- 2021-02-10
insert into part1 (value, gender) values ('criptomoeda', 1);
insert into part1 (value, gender) values ('panda', 0);
insert into part1 (value, gender) values ('saco', 2);
insert into part1 (value, gender) values ('espermatozoide', 2);
insert into part1 (value, gender) values ('membrana', 1);
insert into part1 (value, gender) values ('bagaça', 1);
insert into part1 (value, gender) values ('bagaço', 2);
insert into part1 (value, gender) values ('chá de cogumelo', 2);
insert into part1 (value, gender) values ('cogumelo', 2);
insert into part1 (value, gender) values ('ratoeira', 1);
insert into part1 (value, gender) values ('erro http', 2);
insert into part1 (value, gender) values ('filme de terror', 2);
insert into part1 (value, gender) values ('boquinha', 1);
insert into part1 (value, gender) values ('bocuda', 1);
insert into part1 (value, gender) values ('bocudo', 2);
insert into part1 (value, gender) values ('exorcismo', 2);
insert into part1 (value, gender) values ('caracol', 2);
insert into part1 (value, gender) values ('elefante', 2);
insert into part1 (value, gender) values ('monge', 2);
insert into part1 (value, gender) values ('boneca', 1);
insert into part1 (value, gender) values ('boneco', 2);
insert into part1 (value, gender) values ('bárbara', 1);
insert into part1 (value, gender) values ('bárbaro', 2);
insert into part1 (value, gender) values ('bolinho de arroz', 2);
insert into part1 (value, gender) values ('micróbio', 2);
insert into part1 (value, gender) values ('verme', 2);

insert into part2 (value, gender) values ('na brisa', 0);
insert into part2 (value, gender) values ('atômica', 1);
insert into part2 (value, gender) values ('crosfiteira', 1);
insert into part2 (value, gender) values ('crosfiteiro', 2);
insert into part2 (value, gender) values ('atômico', 2);
insert into part2 (value, gender) values ('sem neurônio', 0);
insert into part2 (value, gender) values ('comedora de bamboo', 1);
insert into part2 (value, gender) values ('comedor de bamboo', 2);
insert into part2 (value, gender) values ('linguaruda', 1);
insert into part2 (value, gender) values ('linguarudo', 2);
insert into part2 (value, gender) values ('despedaçada', 1);
insert into part2 (value, gender) values ('despedaçado', 2);
insert into part2 (value, gender) values ('sem máscara', 0);
insert into part2 (value, gender) values ('desmascarada', 1);
insert into part2 (value, gender) values ('desmascarado', 2);
insert into part2 (value, gender) values ('rabuda', 1);
insert into part2 (value, gender) values ('rabudo', 2);
insert into part2 (value, gender) values ('infantilizada', 1);
insert into part2 (value, gender) values ('infantilizado', 2);
insert into part2 (value, gender) values ('desmembrada', 1);
insert into part2 (value, gender) values ('desmembrado', 2);
insert into part2 (value, gender) values ('liquidificada', 1);
insert into part2 (value, gender) values ('liquidificado', 2);
insert into part2 (value, gender) values ('necromante', 0);
insert into part2 (value, gender) values ('arrombada', 1);
insert into part2 (value, gender) values ('parecida com a Xena', 1);
insert into part2 (value, gender) values ('parecido com a Xena', 2);
insert into part2 (value, gender) values ('maldita', 1);
insert into part2 (value, gender) values ('maldito', 2);
insert into part2 (value, gender) values ('peituda', 1);
insert into part2 (value, gender) values ('espinhuda', 1);
insert into part2 (value, gender) values ('espinhudo', 2);
insert into part2 (value, gender) values ('possuída', 1);
insert into part2 (value, gender) values ('possuído', 2);
insert into part2 (value, gender) values ('feia', 1);
insert into part2 (value, gender) values ('feio', 2);
insert into part2 (value, gender) values ('de chapéu', 0);
insert into part2 (value, gender) values ('branca', 1);
insert into part2 (value, gender) values ('branco', 2);
insert into part2 (value, gender) values ('tibetana', 1);
insert into part2 (value, gender) values ('tibetano', 2);
insert into part2 (value, gender) values ('hentai', 0);

insert into part3 (value, gender) values ('cruzada com o capeta', 1);
insert into part3 (value, gender) values ('cruzado com o capeta', 2);
insert into part3 (value, gender) values ('cor de burro quando foge', 0);
insert into part3 (value, gender) values ('repetente', 0);
insert into part3 (value, gender) values ('na turma do fundão', 0);
insert into part3 (value, gender) values ('que só chega em último lugar', 0);
insert into part3 (value, gender) values ('lambida', 1);
insert into part3 (value, gender) values ('lambido', 2);
insert into part3 (value, gender) values ('verde', 0);
insert into part3 (value, gender) values ('monocromática', 1);
insert into part3 (value, gender) values ('monocromático', 2);
insert into part3 (value, gender) values ('brisada', 0);
insert into part3 (value, gender) values ('investidora de ethereum', 1);
insert into part3 (value, gender) values ('investidor de bitcoin', 2);
insert into part3 (value, gender) values ('do pé torto', 0);
insert into part3 (value, gender) values ('da canela ralada', 0);
insert into part3 (value, gender) values ('extramemente desafinada', 1);
insert into part3 (value, gender) values ('extramemente desafinado', 2);
insert into part3 (value, gender) values ('descendo pelo ralo', 0);
insert into part3 (value, gender) values ('descendo ralo abaixo', 0);
insert into part3 (value, gender) values ('aspirante a princesa guerreira', 0);
insert into part3 (value, gender) values ('que só dá 404', 0);
insert into part3 (value, gender) values ('lactante', 0);
insert into part3 (value, gender) values ('salivante', 0);
insert into part3 (value, gender) values ('que só resmunga', 0);
insert into part3 (value, gender) values ('falida', 1);
insert into part3 (value, gender) values ('falido', 2);
insert into part3 (value, gender) values ('que só sabe tirar onda', 0);
insert into part3 (value, gender) values ('do himalaia', 0);
insert into part3 (value, gender) values ('ondulada', 1);
insert into part3 (value, gender) values ('ondulado', 2);
insert into part3 (value, gender) values ('atropelada', 1);
insert into part3 (value, gender) values ('atropelado', 2);
insert into part3 (value, gender) values ('dubladora de anime', 1);
insert into part3 (value, gender) values ('dublador de anime', 2);
insert into part3 (value, gender) values ('fingindo orgasmo', 0);

-- 2021-02-11
insert into part1 (value, gender) values ('piriguete', 1);
insert into part1 (value, gender) values ('cavala', 1);
insert into part1 (value, gender) values ('cavalo', 2);
insert into part1 (value, gender) values ('cavalinha', 1);
insert into part1 (value, gender) values ('cavalinho', 2);
insert into part1 (value, gender) values ('sua jumenta', 1);
insert into part1 (value, gender) values ('seu jumento', 2);
insert into part1 (value, gender) values ('filha duma égua', 1);
insert into part1 (value, gender) values ('filho duma égua', 2);
insert into part1 (value, gender) values ('sua eguinha', 1);
insert into part1 (value, gender) values ('minha eguinha', 1);
insert into part1 (value, gender) values ('pudim', 2);
insert into part1 (value, gender) values ('seu pau', 2);
insert into part1 (value, gender) values ('pão', 2);
insert into part1 (value, gender) values ('morcego', 2);
insert into part1 (value, gender) values ('que morceguinha', 1);
insert into part1 (value, gender) values ('neurônio', 2);
insert into part1 (value, gender) values ('sua bisnaguinha', 1);
insert into part1 (value, gender) values ('seu bis', 1);
insert into part1 (value, gender) values ('galinha', 1);
insert into part1 (value, gender) values ('galo', 2);
insert into part1 (value, gender) values ('filho de uma piranha', 1);
insert into part1 (value, gender) values ('kpopeira', 1);
insert into part1 (value, gender) values ('kpopeiro', 2);
insert into part1 (value, gender) values ('energético', 2);
insert into part1 (value, gender) values ('borra', 1);
insert into part1 (value, gender) values ('camisinha', 1);
insert into part1 (value, gender) values ('achocolatado', 2);
insert into part1 (value, gender) values ('succubus', 1);
insert into part1 (value, gender) values ('incubus', 2);
insert into part1 (value, gender) values ('buraco negro', 2);
insert into part1 (value, gender) values ('sua simulação', 1);
insert into part1 (value, gender) values ('homem bomba', 2);
insert into part1 (value, gender) values ('mulher bomba', 1);

insert into part2 (value, gender) values ('usada', 1);
insert into part2 (value, gender) values ('usado', 2);
insert into part2 (value, gender) values ('iluminada por fótons', 1);
insert into part2 (value, gender) values ('iluminado por fótons', 2);
insert into part2 (value, gender) values ('em pó', 0);
insert into part2 (value, gender) values ('presa na matrix', 1);
insert into part2 (value, gender) values ('preso na matrix', 2);
insert into part2 (value, gender) values ('de autocomplete', 0);
insert into part2 (value, gender) values ('de café', 0);
insert into part2 (value, gender) values ('sugadora de energia', 1);
insert into part2 (value, gender) values ('sugador de energia', 2);
insert into part2 (value, gender) values ('pocotó', 0);
insert into part2 (value, gender) values ('com vodka', 0);
insert into part2 (value, gender) values ('na aguinha', 0);
insert into part2 (value, gender) values ('dropada', 1);
insert into part2 (value, gender) values ('dropado', 2);
insert into part2 (value, gender) values ('dopada', 1);
insert into part2 (value, gender) values ('dopado', 2);
insert into part2 (value, gender) values ('sertaneja', 1);
insert into part2 (value, gender) values ('sertanejo', 2);
insert into part2 (value, gender) values ('ensopada', 1);
insert into part2 (value, gender) values ('ensopado', 2);
insert into part2 (value, gender) values ('na chapa', 0);
insert into part2 (value, gender) values ('latindo', 0);
insert into part2 (value, gender) values ('de férias', 0);
insert into part2 (value, gender) values ('desconstruída', 1);
insert into part2 (value, gender) values ('desconstruído', 2);
insert into part2 (value, gender) values ('desengonçada', 1);
insert into part2 (value, gender) values ('desengonçado', 2);
insert into part2 (value, gender) values ('sem cabeça', 0);
insert into part2 (value, gender) values ('mordida', 1);
insert into part2 (value, gender) values ('mordido', 2);
insert into part2 (value, gender) values ('ensacada', 1);
insert into part2 (value, gender) values ('ensacado', 2);
insert into part2 (value, gender) values ('d`angola', 0);
insert into part2 (value, gender) values ('sem pescoço', 0);
insert into part2 (value, gender) values ('banguela', 0);
insert into part2 (value, gender) values ('gaseificada', 1);
insert into part2 (value, gender) values ('gaseificado', 2);
insert into part2 (value, gender) values ('sem gás', 0);
insert into part2 (value, gender) values ('que roubou meu coração', 0);
insert into part2 (value, gender) values ('desligada', 1);
insert into part2 (value, gender) values ('desligado', 2);
insert into part2 (value, gender) values ('caramelada', 1);
insert into part2 (value, gender) values ('caramelado', 2);
insert into part2 (value, gender) values ('da cara melada', 0);
insert into part2 (value, gender) values ('dissimulada', 1);
insert into part2 (value, gender) values ('dissimulado', 2);
insert into part2 (value, gender) values ('de shortinho', 0);
insert into part2 (value, gender) values ('de saia', 0);

insert into part3 (value, gender) values ('dentro de uma simulação', 0);
insert into part3 (value, gender) values ('parecida com o godzilla', 1);
insert into part3 (value, gender) values ('parecido com o godzilla', 2);
insert into part3 (value, gender) values ('mas não vale nem um centavo', 0);
insert into part3 (value, gender) values ('mas não vale nada', 0);
insert into part3 (value, gender) values ('na escuridão', 0);
insert into part3 (value, gender) values ('bandida', 1);
insert into part3 (value, gender) values ('bandido', 2);
insert into part3 (value, gender) values ('criminosa', 1);
insert into part3 (value, gender) values ('criminoso', 2);
insert into part3 (value, gender) values ('desmiolada', 1);
insert into part3 (value, gender) values ('desmiolado', 2);
insert into part3 (value, gender) values ('descafeinada', 1);
insert into part3 (value, gender) values ('descafeinado', 2);
insert into part3 (value, gender) values ('sem taurina', 0);
insert into part3 (value, gender) values ('sem bolinhas', 0);
insert into part3 (value, gender) values ('sem bola', 0);
insert into part3 (value, gender) values ('sem pai', 0);
insert into part3 (value, gender) values ('encerada', 1);
insert into part3 (value, gender) values ('encerado', 2);
insert into part3 (value, gender) values ('prensada', 1);
insert into part3 (value, gender) values ('prensado', 2);
insert into part3 (value, gender) values ('igual o cachorro do vizinho', 0);
insert into part3 (value, gender) values ('sem legado', 0);
insert into part3 (value, gender) values ('que o diabo amassou', 0);
insert into part3 (value, gender) values ('em conserva', 0);
insert into part3 (value, gender) values ('na laje', 0);
insert into part3 (value, gender) values ('pela metade', 0);
insert into part3 (value, gender) values ('pocotó pocotó', 0);
insert into part3 (value, gender) values ('desnatada', 1);
insert into part3 (value, gender) values ('desnatado', 2);
insert into part3 (value, gender) values ('integral', 0);
insert into part3 (value, gender) values ('de fio dental', 0);
insert into part3 (value, gender) values ('gozada', 1);
insert into part3 (value, gender) values ('gozado', 2);
insert into part3 (value, gender) values ('gozadinha', 1);
insert into part3 (value, gender) values ('gozadinho', 2);
insert into part3 (value, gender) values ('durante a cremação', 0);
insert into part3 (value, gender) values ('no meio da cremação', 0);
insert into part3 (value, gender) values ('em processo de decomposição', 0);
insert into part3 (value, gender) values ('atolada', 1);
insert into part3 (value, gender) values ('atolado', 2);
insert into part3 (value, gender) values ('atoladinha', 1);
insert into part3 (value, gender) values ('atoladinho', 2);

-- 2021-02-12
insert into part1 (value, gender) values ('cérebro de vaca', 2);
insert into part1 (value, gender) values ('analfabeta', 1);
insert into part1 (value, gender) values ('analfabeto', 2);
insert into part1 (value, gender) values ('protozoário', 2);
insert into part1 (value, gender) values ('anis estrelado', 2);
insert into part1 (value, gender) values ('vuvuzela', 1);
insert into part1 (value, gender) values ('unha', 1);
insert into part1 (value, gender) values ('tooltip', 2);
insert into part1 (value, gender) values ('milha', 1);
insert into part1 (value, gender) values ('milho', 2);
insert into part1 (value, gender) values ('broto', 2);
insert into part1 (value, gender) values ('feijoada', 1);
insert into part1 (value, gender) values ('commit', 2);
insert into part1 (value, gender) values ('lactobacilo', 2);
insert into part1 (value, gender) values ('dedada', 1);
insert into part1 (value, gender) values ('porta', 1);

insert into part2 (value, gender) values ('pré histórica', 1);
insert into part2 (value, gender) values ('pré histórico', 2);
insert into part2 (value, gender) values ('do poço', 0);
insert into part2 (value, gender) values ('mal depilada', 1);
insert into part2 (value, gender) values ('mal depilado', 2);
insert into part2 (value, gender) values ('com encefalopatia espongiforme', 0);
insert into part2 (value, gender) values ('funcional', 0);
insert into part2 (value, gender) values ('megalomaníaca', 1);
insert into part2 (value, gender) values ('megalomaníaco', 2);
insert into part2 (value, gender) values ('com cara de', 0);
insert into part2 (value, gender) values ('com a cara', 0);
insert into part2 (value, gender) values ('que parece que tomou uma pintada', 0);
insert into part2 (value, gender) values ('espatifada', 1);
insert into part2 (value, gender) values ('espatifado', 2);
insert into part2 (value, gender) values ('qualhada', 1);
insert into part2 (value, gender) values ('qualhado', 2);
insert into part2 (value, gender) values ('mal pintada', 1);
insert into part2 (value, gender) values ('mal pintado', 2);
insert into part2 (value, gender) values ('escorregadia', 1);
insert into part2 (value, gender) values ('escorregadio', 2);
insert into part2 (value, gender) values ('desalinhada', 1);
insert into part2 (value, gender) values ('desalinhado', 2);
insert into part2 (value, gender) values ('lunática', 1);
insert into part2 (value, gender) values ('lunático', 2);
insert into part2 (value, gender) values ('náutica', 1);
insert into part2 (value, gender) values ('náutico', 2);
insert into part2 (value, gender) values ('de feijão', 2);
insert into part2 (value, gender) values ('viva', 1);
insert into part2 (value, gender) values ('vivo', 2);
insert into part2 (value, gender) values ('sem sinal', 0);
insert into part2 (value, gender) values ('salafrária', 1);
insert into part2 (value, gender) values ('salafrário', 2);
insert into part2 (value, gender) values ('do deserto', 0);
insert into part2 (value, gender) values ('com parkinson', 0);
insert into part2 (value, gender) values ('jurássica', 1);
insert into part2 (value, gender) values ('jurássico', 2);
insert into part2 (value, gender) values ('burra', 1);
insert into part2 (value, gender) values ('burro', 2);

insert into part3 (value, gender) values ('da turma do fundão', 0);
insert into part3 (value, gender) values ('da cara pintada', 0);
insert into part3 (value, gender) values ('na cara', 0);
insert into part3 (value, gender) values ('e borrada', 1);
insert into part3 (value, gender) values ('e borrado', 2);
insert into part3 (value, gender) values ('no chão', 0);
insert into part3 (value, gender) values ('desdentada', 1);
insert into part3 (value, gender) values ('desdentado', 2);
insert into part3 (value, gender) values ('azeda', 1);
insert into part3 (value, gender) values ('azedo', 2);
insert into part3 (value, gender) values ('mofada', 1);
insert into part3 (value, gender) values ('mofado', 2);
insert into part3 (value, gender) values ('envenenada', 1);
insert into part3 (value, gender) values ('envenenado', 2);
insert into part3 (value, gender) values ('que só enche o saco', 0);
insert into part3 (value, gender) values ('com a lerdeza de um slowpoke', 0);
insert into part3 (value, gender) values ('sem revisão', 0);
insert into part3 (value, gender) values ('pendente de revisão', 0);
insert into part3 (value, gender) values ('na vida', 0);
insert into part3 (value, gender) values ('sem vida', 0);
insert into part3 (value, gender) values ('da tim', 0);
insert into part3 (value, gender) values ('mesmo', 0);
insert into part3 (value, gender) values ('paga pau', 0);
insert into part3 (value, gender) values ('feito uma porta', 0);
insert into part3 (value, gender) values ('grossa', 1);
insert into part3 (value, gender) values ('grosso', 2);

-- 2021-02-20
insert into part1 (value, gender) values ('traíra', 1);
insert into part1 (value, gender) values ('arraia', 1);
insert into part1 (value, gender) values ('otome', 1);
insert into part1 (value, gender) values ('otaku', 2);

insert into part2 (value, gender) values ('gigante', 0);
insert into part2 (value, gender) values ('imatura', 1);
insert into part2 (value, gender) values ('imaturo', 2);
insert into part2 (value, gender) values ('encravada', 1);
insert into part2 (value, gender) values ('encravado', 2);
insert into part2 (value, gender) values ('mal desenvolvida', 1);
insert into part2 (value, gender) values ('mal desenvolvido', 2);
insert into part2 (value, gender) values ('duvidosa', 1);
insert into part2 (value, gender) values ('duvidoso', 2);

insert into part3 (value, gender) values ('x9', 0);
insert into part3 (value, gender) values ('emputecida', 1);
insert into part3 (value, gender) values ('emputecido', 2);
insert into part3 (value, gender) values ('totalmente nada a ver', 0);
insert into part3 (value, gender) values ('chapada', 1);
insert into part3 (value, gender) values ('chapado', 2);
insert into part3 (value, gender) values ('meramente ilustrativa', 1);
insert into part3 (value, gender) values ('meramente ilustrativo', 2);
insert into part3 (value, gender) values ('nada didática', 1);
insert into part3 (value, gender) values ('nada didático', 2);

-- 2021-02-21
insert into part0 (value, gender) values ('mas que', 0);
insert into part0 (value, gender) values ('bolo de', 0);
insert into part0 (value, gender) values ('calma', 0);
insert into part0 (value, gender) values ('forma de', 0);
insert into part0 (value, gender) values ('projeto de', 0);
insert into part0 (value, gender) values ('ah, vai sua', 1);
insert into part0 (value, gender) values ('ah, vai seu', 2);
insert into part0 (value, gender) values ('nem vale a pena essa', 1);
insert into part0 (value, gender) values ('nem vale a pena esse', 2);

insert into part1 (value, gender) values ('bruschetta', 1);
insert into part1 (value, gender) values ('corcunda', 0);
insert into part1 (value, gender) values ('vala', 1);
insert into part1 (value, gender) values ('gelo', 2);
insert into part1 (value, gender) values ('sapa', 1);
insert into part1 (value, gender) values ('sapo', 2);
insert into part1 (value, gender) values ('rabisco', 2);
insert into part1 (value, gender) values ('minhoca', 1);
insert into part1 (value, gender) values ('minhoco', 2);
insert into part1 (value, gender) values ('papagaia', 1);
insert into part1 (value, gender) values ('papagaio', 2);
insert into part1 (value, gender) values ('pararraio', 2);
insert into part1 (value, gender) values ('quenga', 1);
insert into part1 (value, gender) values ('stick', 2);
insert into part1 (value, gender) values ('erro ortográfico', 2);
insert into part1 (value, gender) values ('governo', 2);
insert into part1 (value, gender) values ('geleia de goiaba', 1);
insert into part1 (value, gender) values ('geleia', 1);
insert into part1 (value, gender) values ('tamanduá', 2);
insert into part1 (value, gender) values ('traquitana', 1);

insert into part2 (value, gender) values ('erguida', 1);
insert into part2 (value, gender) values ('erguido', 2);
insert into part2 (value, gender) values ('liquiforme', 0);
insert into part2 (value, gender) values ('de peixe', 2);
insert into part2 (value, gender) values ('invertida', 1);
insert into part2 (value, gender) values ('invertido', 2);
insert into part2 (value, gender) values ('amolada', 1);
insert into part2 (value, gender) values ('amolado', 2);
insert into part2 (value, gender) values ('mal amolada', 1);
insert into part2 (value, gender) values ('mal amolado', 2);
insert into part2 (value, gender) values ('avoada', 1);
insert into part2 (value, gender) values ('avoado', 2);
insert into part2 (value, gender) values ('desequilibrada', 1);
insert into part2 (value, gender) values ('desequilibrado', 2);
insert into part2 (value, gender) values ('relichante', 0);
insert into part2 (value, gender) values ('rastejante', 0);
insert into part2 (value, gender) values ('ansiosa', 1);
insert into part2 (value, gender) values ('ansioso', 2);
insert into part2 (value, gender) values ('parametrizada', 1);
insert into part2 (value, gender) values ('parametrizado', 2);
insert into part2 (value, gender) values ('desparametrizada', 1);
insert into part2 (value, gender) values ('desparametrizado', 2);
insert into part2 (value, gender) values ('desfuncional', 0);
insert into part2 (value, gender) values ('split', 0);
insert into part2 (value, gender) values ('de criança', 0);
insert into part2 (value, gender) values ('afogada', 1);
insert into part2 (value, gender) values ('afogado', 2);
insert into part2 (value, gender) values ('eletrizada', 1);
insert into part2 (value, gender) values ('eletrizado', 2);
insert into part2 (value, gender) values ('circense', 0);
insert into part2 (value, gender) values ('de circo', 0);
insert into part2 (value, gender) values ('analógica', 1);
insert into part2 (value, gender) values ('analógico', 2);
insert into part2 (value, gender) values ('depilada', 1);
insert into part2 (value, gender) values ('depilado', 2);
insert into part2 (value, gender) values ('semântica', 1);
insert into part2 (value, gender) values ('semântico', 2);
insert into part2 (value, gender) values ('desenhada no paint', 1);
insert into part2 (value, gender) values ('desenhado no paint', 2);
insert into part2 (value, gender) values ('suicida', 0);
insert into part2 (value, gender) values ('enrugada', 1);
insert into part2 (value, gender) values ('enrugado', 2);
insert into part2 (value, gender) values ('decepada', 1);
insert into part2 (value, gender) values ('decepado', 2);
insert into part2 (value, gender) values ('saída do poço', 1);
insert into part2 (value, gender) values ('saído do poço', 2);
insert into part2 (value, gender) values ('bleh', 0);
insert into part2 (value, gender) values ('marinada', 1);
insert into part2 (value, gender) values ('marinado', 2);
insert into part2 (value, gender) values ('laminada', 1);
insert into part2 (value, gender) values ('laminado', 2);

insert into part3 (value, gender) values ('anguiliforme', 0);
insert into part3 (value, gender) values ('que não lava o pé', 0);
insert into part3 (value, gender) values ('meio depressiva', 1);
insert into part3 (value, gender) values ('meio depressivo', 2);
insert into part3 (value, gender) values ('na fábrica', 0);
insert into part3 (value, gender) values ('do norte', 2);
insert into part3 (value, gender) values ('desgastada', 1);
insert into part3 (value, gender) values ('desgastado', 2);
insert into part3 (value, gender) values ('gramatical', 0);
insert into part3 (value, gender) values ('com mouse de bolinha', 0);
insert into part3 (value, gender) values ('num monitor de tubo', 0);
insert into part3 (value, gender) values ('vergonha da profission', 0);
insert into part3 (value, gender) values ('ultrapassada', 1);
insert into part3 (value, gender) values ('ultrapassado', 2);
insert into part3 (value, gender) values ('da casa do chapéu', 0);
insert into part3 (value, gender) values ('de onde judas perdeu as botas', 0);
insert into part3 (value, gender) values ('mineradora de ethereum', 1);
insert into part3 (value, gender) values ('mineradora de bitcoin', 1);
insert into part3 (value, gender) values ('minerador de ethereum', 2);
insert into part3 (value, gender) values ('minerador de bitcoin', 2);
insert into part3 (value, gender) values ('mal identada', 1);
insert into part3 (value, gender) values ('mal identado', 2);
insert into part3 (value, gender) values ('amargurada', 1);
insert into part3 (value, gender) values ('amargurado', 2);
insert into part3 (value, gender) values ('sinuosa', 1);
insert into part3 (value, gender) values ('sinuoso', 2);
insert into part3 (value, gender) values ('no canavial', 0);
insert into part3 (value, gender) values ('parecida com a kitana', 1);
insert into part3 (value, gender) values ('parecido com a kitana', 2);
insert into part3 (value, gender) values ('vagabunda', 1);
insert into part3 (value, gender) values ('vagabundo', 2);
insert into part3 (value, gender) values ('bleh bleh', 0);
insert into part3 (value, gender) values ('suspensa', 1);
insert into part3 (value, gender) values ('suspenso', 2);

-- 2021-03-08
insert into part0 (value, gender) values ('quem sou eu pra questionar essa', 1);
insert into part0 (value, gender) values ('quem sou eu pra questionar esse', 2);
insert into part0 (value, gender) values ('chupa', 0);
insert into part0 (value, gender) values ('transformadora', 1);
insert into part0 (value, gender) values ('transformador', 2);
insert into part0 (value, gender) values ('usuária de', 1);
insert into part0 (value, gender) values ('usuário de', 2);
insert into part0 (value, gender) values ('af sua', 1);
insert into part0 (value, gender) values ('af seu', 2);
insert into part0 (value, gender) values ('af que', 0);
insert into part0 (value, gender) values ('af... ', 0);
insert into part0 (value, gender) values ('af! ', 0);
insert into part0 (value, gender) values ('af, ', 0);

insert into part1 (value, gender) values ('meme', 2);
insert into part1 (value, gender) values ('bolota', 1);
insert into part1 (value, gender) values ('pica pau', 2);
insert into part1 (value, gender) values ('funcionário público', 2);
insert into part1 (value, gender) values ('funcionária pública', 1);
insert into part1 (value, gender) values ('luz', 1);
insert into part1 (value, gender) values ('lagosta', 1);
insert into part1 (value, gender) values ('piada', 1);
insert into part1 (value, gender) values ('jump scare', 2);
insert into part1 (value, gender) values ('receita', 1);
insert into part1 (value, gender) values ('bunda', 1);
insert into part1 (value, gender) values ('bundão', 2);
insert into part1 (value, gender) values ('corno', 2);
insert into part1 (value, gender) values ('pé', 2);
insert into part1 (value, gender) values ('vagalume', 2);
insert into part1 (value, gender) values ('enguia', 1);
insert into part1 (value, gender) values ('pia', 1);
insert into part1 (value, gender) values ('pintinha', 1);
insert into part1 (value, gender) values ('pintinho', 2);
insert into part1 (value, gender) values ('pata', 1);
insert into part1 (value, gender) values ('pato', 2);
insert into part1 (value, gender) values ('alarme', 2);
insert into part1 (value, gender) values ('despertador', 2);
insert into part1 (value, gender) values ('canabidiol', 2);
insert into part1 (value, gender) values ('cannabis', 1);

insert into part2 (value, gender) values ('de posto', 0);
insert into part2 (value, gender) values ('do pasto', 0);
insert into part2 (value, gender) values ('cara', 1);
insert into part2 (value, gender) values ('caro', 2);
insert into part2 (value, gender) values ('viciada em facebook', 1);
insert into part2 (value, gender) values ('viciado em facebook', 2);
insert into part2 (value, gender) values ('rouca', 1);
insert into part2 (value, gender) values ('rouco', 2);
insert into part2 (value, gender) values ('agonizante', 0);
insert into part2 (value, gender) values ('infinita', 1);
insert into part2 (value, gender) values ('infinito', 2);
insert into part2 (value, gender) values ('cetogênica', 1);
insert into part2 (value, gender) values ('cetogênico', 2);
insert into part2 (value, gender) values ('descongelada', 1);
insert into part2 (value, gender) values ('descongelado', 2);
insert into part2 (value, gender) values ('desparafusada', 1);
insert into part2 (value, gender) values ('desparafusado', 2);
insert into part2 (value, gender) values ('parafusada', 1);
insert into part2 (value, gender) values ('parafusado', 2);
insert into part2 (value, gender) values ('enguiçada', 1);
insert into part2 (value, gender) values ('sistemática', 1);
insert into part2 (value, gender) values ('sistemático', 2);
insert into part2 (value, gender) values ('metódica', 1);
insert into part2 (value, gender) values ('metódico', 2);
insert into part2 (value, gender) values ('lixo', 2);
insert into part2 (value, gender) values ('bolando', 0);
insert into part2 (value, gender) values ('postando', 0);
insert into part2 (value, gender) values ('de calça', 1);
insert into part2 (value, gender) values ('de calça legging', 1);
insert into part2 (value, gender) values ('pregada', 1);
insert into part2 (value, gender) values ('pregado', 2);
insert into part2 (value, gender) values ('nariguda', 1);
insert into part2 (value, gender) values ('narigudo', 2);
insert into part2 (value, gender) values ('quadrangular', 0);
insert into part2 (value, gender) values ('triangular', 0);
insert into part2 (value, gender) values ('hexagonal', 0);
insert into part2 (value, gender) values ('de trigo', 0);
insert into part2 (value, gender) values ('quilométrica', 1);
insert into part2 (value, gender) values ('quilométrico', 2);
insert into part2 (value, gender) values ('autista', 0);
insert into part2 (value, gender) values ('assustada', 1);
insert into part2 (value, gender) values ('assustado', 2);
insert into part2 (value, gender) values ('escondida', 1);
insert into part2 (value, gender) values ('escondido', 2);
insert into part2 (value, gender) values ('acionista', 0);
insert into part2 (value, gender) values ('revolucionária', 1);
insert into part2 (value, gender) values ('revolucionário', 2);
insert into part2 (value, gender) values ('reacionária', 1);
insert into part2 (value, gender) values ('reacionário', 2);
insert into part2 (value, gender) values ('conservadora', 1);
insert into part2 (value, gender) values ('conservador', 2);

insert into part3 (value, gender) values ('num painel fotovoltaico', 0);
insert into part3 (value, gender) values ('que fala alto demais', 0);
insert into part3 (value, gender) values ('que fala demais', 0);
insert into part3 (value, gender) values ('que não para de falar', 0);
insert into part3 (value, gender) values ('que fala mais que a minha mãe', 0);
insert into part3 (value, gender) values ('volumétrica', 1);
insert into part3 (value, gender) values ('volumétrico', 2);
insert into part3 (value, gender) values ('voltaica', 1);
insert into part3 (value, gender) values ('voltaico', 2);
insert into part3 (value, gender) values ('sem fusível', 0);
insert into part3 (value, gender) values ('sem volume', 0);
insert into part3 (value, gender) values ('trigonométrica', 1);
insert into part3 (value, gender) values ('trigonométrico', 2);
insert into part3 (value, gender) values ('resto de uma raíz quadrática', 0);
insert into part3 (value, gender) values ('do nariz triangular', 0);
insert into part3 (value, gender) values ('fora da tomada', 0);
insert into part3 (value, gender) values ('na tomada', 0);
insert into part3 (value, gender) values ('ligada no 220', 1);
insert into part3 (value, gender) values ('ligado no 220', 2);
insert into part3 (value, gender) values ('na cruz', 0);
insert into part3 (value, gender) values ('e crucificada', 1);
insert into part3 (value, gender) values ('e crucificado', 2);
insert into part3 (value, gender) values ('melada', 1);
insert into part3 (value, gender) values ('melado', 2);
insert into part3 (value, gender) values ('atordoada', 1);
insert into part3 (value, gender) values ('atordoado', 2);
insert into part3 (value, gender) values ('retardado', 0);
insert into part3 (value, gender) values ('psolista', 0);
insert into part3 (value, gender) values ('petista', 0);
insert into part3 (value, gender) values ('bolsonarista', 0);
insert into part3 (value, gender) values ('lulopetista', 0);
insert into part3 (value, gender) values ('bolsolulista', 0);
insert into part3 (value, gender) values ('que não pisca mais', 0);
insert into part3 (value, gender) values ('apertada', 0);
insert into part3 (value, gender) values ('numa câmara criogênica', 0);
insert into part3 (value, gender) values ('aterrorizante', 0);
insert into part3 (value, gender) values ('encaixotada', 1);
insert into part3 (value, gender) values ('encaixotado', 2);
insert into part3 (value, gender) values ('abafada', 1);
insert into part3 (value, gender) values ('abafado', 2);
insert into part3 (value, gender) values ('afobada', 1);
insert into part3 (value, gender) values ('afobado', 2);
insert into part3 (value, gender) values ('entrelaçada', 1);
insert into part3 (value, gender) values ('entrelaçado', 2);
insert into part3 (value, gender) values ('venenosa', 1);
insert into part3 (value, gender) values ('venenoso', 2);
insert into part3 (value, gender) values ('estrondosa', 1);
insert into part3 (value, gender) values ('estrondoso', 2);
insert into part3 (value, gender) values ('num tom jocoso', 0);
insert into part3 (value, gender) values ('de touca', 0);
insert into part3 (value, gender) values ('na toca', 0);
insert into part3 (value, gender) values ('que não me deixa dormir', 0);
insert into part3 (value, gender) values ('que não me deixa dormir à noite', 0);
insert into part3 (value, gender) values ('que não me deixa acordar', 0);
insert into part3 (value, gender) values ('que não me deixa acordar cedo', 0);
insert into part3 (value, gender) values ('que só acorda depois do meio dia', 0);
insert into part3 (value, gender) values ('depois do meio dia', 0);
insert into part3 (value, gender) values ('depois da meia noite', 0);
insert into part3 (value, gender) values ('depois do crepúsculo', 0);
insert into part3 (value, gender) values ('sem músculo', 0);
insert into part3 (value, gender) values ('musculosa', 1);
insert into part3 (value, gender) values ('musculoso', 2);
insert into part3 (value, gender) values ('que só acende quando quer', 0);
insert into part3 (value, gender) values ('no cinzeiro', 0);
insert into part3 (value, gender) values ('sem cheiro', 0);
insert into part3 (value, gender) values ('do cheiro horrível', 0);
insert into part3 (value, gender) values ('revoltada', 1);
insert into part3 (value, gender) values ('revoltado', 2);
insert into part3 (value, gender) values ('pago com dinheiro público', 0);
insert into part3 (value, gender) values ('sem pé', 0);
insert into part3 (value, gender) values ('do avesso', 0);
insert into part3 (value, gender) values ('de mimimi', 0);
insert into part3 (value, gender) values ('de cu doce', 0);
insert into part3 (value, gender) values ('mimimizenta', 1);
insert into part3 (value, gender) values ('mimimizento', 2);
insert into part3 (value, gender) values ('passapanista', 0);

-- 2021-03-15
insert into part0 (value, gender) values ('cara de', 0);

insert into part1 (value, gender) values ('saci', 2);
insert into part1 (value, gender) values ('cabra', 1);
insert into part1 (value, gender) values ('tumba', 1);
insert into part1 (value, gender) values ('tequila', 1);
insert into part1 (value, gender) values ('político', 2);
insert into part1 (value, gender) values ('vereadora', 1);
insert into part1 (value, gender) values ('vereador', 2);
insert into part1 (value, gender) values ('palhaça', 1);
insert into part1 (value, gender) values ('palhaço', 2);
insert into part1 (value, gender) values ('meretriz', 1);
insert into part1 (value, gender) values ('caipora', 1);

insert into part2 (value, gender) values ('asmática', 1);
insert into part2 (value, gender) values ('asmático', 2);
insert into part2 (value, gender) values ('lavada', 1);
insert into part2 (value, gender) values ('lavado', 2);
insert into part2 (value, gender) values ('profanadora', 1);
insert into part2 (value, gender) values ('profanador', 2);
insert into part2 (value, gender) values ('profanada', 1);
insert into part2 (value, gender) values ('profanado', 2);
insert into part2 (value, gender) values ('aposentada', 1);
insert into part2 (value, gender) values ('aposentado', 2);
insert into part2 (value, gender) values ('acumulada', 1);
insert into part2 (value, gender) values ('acumulado', 2);
insert into part2 (value, gender) values ('estatista', 0);
insert into part2 (value, gender) values ('estatal', 0);
insert into part2 (value, gender) values ('barata', 1);
insert into part2 (value, gender) values ('barato', 2);
insert into part2 (value, gender) values ('rigorosamente', 0);
insert into part2 (value, gender) values ('pragmática', 1);
insert into part2 (value, gender) values ('pragmático', 2);
insert into part2 (value, gender) values ('desprendida', 1);
insert into part2 (value, gender) values ('desprendido', 2);
insert into part2 (value, gender) values ('perneta', 0);

insert into part3 (value, gender) values ('pulando numa perna só', 0);
insert into part3 (value, gender) values ('mal lavada', 1);
insert into part3 (value, gender) values ('mal lavado', 2);
insert into part3 (value, gender) values ('da augusta', 0);
insert into part3 (value, gender) values ('ridícula', 1);
insert into part3 (value, gender) values ('ridículo', 2);
insert into part3 (value, gender) values ('singela', 1);
insert into part3 (value, gender) values ('singelo', 2);
insert into part3 (value, gender) values ('a rigor', 0);
insert into part3 (value, gender) values ('criadora de auxílio', 1);
insert into part3 (value, gender) values ('criador de auxílio', 2);
insert into part3 (value, gender) values ('morrendo de asma', 0);

-- 2021-06-24
insert into part0 (value, gender) values ('dra.', 1);
insert into part0 (value, gender) values ('dr.', 2);
insert into part0 (value, gender) values ('mestra em', 1);
insert into part0 (value, gender) values ('mestre em', 2);

insert into part1 (value, gender) values ('pãozinho', 2);
insert into part1 (value, gender) values ('bexiga', 1);
insert into part1 (value, gender) values ('mendiga', 1);
insert into part1 (value, gender) values ('mendigo', 2);
insert into part1 (value, gender) values ('carinha', 1);
insert into part1 (value, gender) values ('carinho', 2);
insert into part1 (value, gender) values ('presepada', 1);
insert into part1 (value, gender) values ('pacote', 2);
insert into part1 (value, gender) values ('vacina', 1);
insert into part1 (value, gender) values ('ensino', 2);
insert into part1 (value, gender) values ('doutora', 1);
insert into part1 (value, gender) values ('doutor', 2);
insert into part1 (value, gender) values ('sacola', 1);
insert into part1 (value, gender) values ('jiboia', 1);
insert into part1 (value, gender) values ('clone', 2);
insert into part1 (value, gender) values ('psicopata', 0);
insert into part1 (value, gender) values ('plástico', 2);
insert into part1 (value, gender) values ('adúltera', 1);
insert into part1 (value, gender) values ('adúltero', 2);
insert into part1 (value, gender) values ('buraco', 2);
insert into part1 (value, gender) values ('macaca', 1);
insert into part1 (value, gender) values ('macaco', 2);
insert into part1 (value, gender) values ('cebolete', 2);
insert into part1 (value, gender) values ('bafo', 2);
insert into part1 (value, gender) values ('hipismo', 2);
insert into part1 (value, gender) values ('bebedora', 1);
insert into part1 (value, gender) values ('bebedor', 2);
insert into part1 (value, gender) values ('balalaika', 1);
insert into part1 (value, gender) values ('corote', 2);

insert into part2 (value, gender) values ('rosa', 1);
insert into part2 (value, gender) values ('lambedora', 1);
insert into part2 (value, gender) values ('lambedor', 2);
insert into part2 (value, gender) values ('hipnótica', 1);
insert into part2 (value, gender) values ('hipnótico', 2);
insert into part2 (value, gender) values ('embalsamada', 1);
insert into part2 (value, gender) values ('embalsamado', 2);
insert into part2 (value, gender) values ('escalafobética', 1);
insert into part2 (value, gender) values ('escalafobético', 2);
insert into part2 (value, gender) values ('incongruente', 0);
insert into part2 (value, gender) values ('indeterminável', 0);
insert into part2 (value, gender) values ('low carb', 0);
insert into part2 (value, gender) values ('de dinossaura', 1);
insert into part2 (value, gender) values ('de dinossauro', 2);
insert into part2 (value, gender) values ('com uma mão no volante', 0);
insert into part2 (value, gender) values ('épica', 1);
insert into part2 (value, gender) values ('épico', 2);
insert into part2 (value, gender) values ('da pfizer', 0);
insert into part2 (value, gender) values ('superior', 0);
insert into part2 (value, gender) values ('inferior', 0);
insert into part2 (value, gender) values ('lateral', 0);
insert into part2 (value, gender) values ('com doutorado', 0);
insert into part2 (value, gender) values ('com mestrado', 0);
insert into part2 (value, gender) values ('com bacharelado', 0);
insert into part2 (value, gender) values ('phd', 0);
insert into part2 (value, gender) values ('de sabão', 0);
insert into part2 (value, gender) values ('de rolha', 0);
insert into part2 (value, gender) values ('com figurinhas', 1);
insert into part2 (value, gender) values ('de cartão', 0);
insert into part2 (value, gender) values ('de cartão de crédito', 0);
insert into part2 (value, gender) values ('bocó', 0);
insert into part2 (value, gender) values ('rococó', 0);
insert into part2 (value, gender) values ('quente', 0);
insert into part2 (value, gender) values ('fria', 1);
insert into part2 (value, gender) values ('frio', 2);
insert into part2 (value, gender) values ('anti', 0);
insert into part2 (value, gender) values ('martelando', 0);
insert into part2 (value, gender) values ('sanguinária', 1);
insert into part2 (value, gender) values ('sanguinário', 2);
insert into part2 (value, gender) values ('albina', 1);
insert into part2 (value, gender) values ('albino', 2);
insert into part2 (value, gender) values ('embasbacada', 1);
insert into part2 (value, gender) values ('embasbacado', 2);

insert into part3 (value, gender) values ('paralela', 1);
insert into part3 (value, gender) values ('paralelo', 2);
insert into part3 (value, gender) values ('eufórica', 1);
insert into part3 (value, gender) values ('eufórico', 2);
insert into part3 (value, gender) values ('homofóbica', 1);
insert into part3 (value, gender) values ('homofóbico', 2);
insert into part3 (value, gender) values ('transfóbica', 1);
insert into part3 (value, gender) values ('transfóbico', 2);
insert into part3 (value, gender) values ('corrupta', 1);
insert into part3 (value, gender) values ('corrupto', 2);
insert into part3 (value, gender) values ('corrompida', 1);
insert into part3 (value, gender) values ('corrompido', 2);
insert into part3 (value, gender) values ('da apple', 0);
insert into part3 (value, gender) values ('de manhã', 0);
insert into part3 (value, gender) values ('jogadora de poker', 1);
insert into part3 (value, gender) values ('jogador de poker', 2);
insert into part3 (value, gender) values ('fazendo carinho', 0);
insert into part3 (value, gender) values ('pior que astrazeneca', 0);
insert into part3 (value, gender) values ('em fazendinha', 0);
insert into part3 (value, gender) values ('de caramelo', 0);
insert into part3 (value, gender) values ('caramelizada', 1);
insert into part3 (value, gender) values ('caramelizado', 2);
insert into part3 (value, gender) values ('adesiva', 1);
insert into part3 (value, gender) values ('adesivo', 2);
insert into part3 (value, gender) values ('que cresceu com home schooling', 0);
insert into part3 (value, gender) values ('de papel', 0);
insert into part3 (value, gender) values ('clonada', 1);
insert into part3 (value, gender) values ('clonado', 2);
insert into part3 (value, gender) values ('despirocada', 1);
insert into part3 (value, gender) values ('despirocado', 2);
insert into part3 (value, gender) values ('molhadinha', 1);
insert into part3 (value, gender) values ('molhadinho', 2);
insert into part3 (value, gender) values ('meladinha', 1);
insert into part3 (value, gender) values ('meladinho', 2);
insert into part3 (value, gender) values ('molhada', 1);
insert into part3 (value, gender) values ('molhado', 2);
insert into part3 (value, gender) values ('pisoteada', 1);
insert into part3 (value, gender) values ('pisoteado', 2);
insert into part3 (value, gender) values ('de brócolis', 0);
insert into part3 (value, gender) values ('morrendo de bri', 0);
insert into part3 (value, gender) values ('que só usa oral-b complete', 0);

-- 2022-06-15
insert into part0 (value, gender) values ('impressora de', 1);
insert into part0 (value, gender) values ('impressor de', 2);
insert into part0 (value, gender) values ('vem', 0);
insert into part0 (value, gender) values ('vai', 0);
insert into part0 (value, gender) values ('ah', 0);
insert into part0 (value, gender) values ('mais velha que uma', 1);
insert into part0 (value, gender) values ('mais velho que um', 2);

insert into part1 (value, gender) values ('motogirl', 1);
insert into part1 (value, gender) values ('motoboy', 2);
insert into part1 (value, gender) values ('jardinagem', 1);
insert into part1 (value, gender) values ('coca-cola', 1);
insert into part1 (value, gender) values ('pepsi', 1);
insert into part1 (value, gender) values ('pirata', 0);
insert into part1 (value, gender) values ('viking', 0);
insert into part1 (value, gender) values ('labareda', 1);
insert into part1 (value, gender) values ('cantora', 1);
insert into part1 (value, gender) values ('cantor', 2);
insert into part1 (value, gender) values ('machista', 0);
insert into part1 (value, gender) values ('misoginista', 0);
insert into part1 (value, gender) values ('supremacista', 0);

insert into part2 (value, gender) values ('raquítica', 1);
insert into part2 (value, gender) values ('raquítico', 2);
insert into part2 (value, gender) values ('na plantação', 1);
insert into part2 (value, gender) values ('esquerdista', 0);
insert into part2 (value, gender) values ('hétero', 0);
insert into part2 (value, gender) values ('hétero-top', 0);
insert into part2 (value, gender) values ('safadinha', 1);
insert into part2 (value, gender) values ('safadinho', 2);
insert into part2 (value, gender) values ('lazarenta', 1);
insert into part2 (value, gender) values ('lazarento', 2);
insert into part2 (value, gender) values ('quicando', 0);
insert into part2 (value, gender) values ('trincando', 0);
insert into part2 (value, gender) values ('socialista', 0);
insert into part2 (value, gender) values ('comunista', 0);
insert into part2 (value, gender) values ('coça-coça', 0);
insert into part2 (value, gender) values ('zipada', 1);
insert into part2 (value, gender) values ('zipado', 0);
insert into part2 (value, gender) values ('parecida com o Silvio Santos', 1);
insert into part2 (value, gender) values ('parecido com o Silvio Santos', 2);

insert into part3 (value, gender) values ('de busão', 0);
insert into part3 (value, gender) values ('no busão', 0);
insert into part3 (value, gender) values ('mais burra que o monark', 1);
insert into part3 (value, gender) values ('mais burro que o monark', 2);
insert into part3 (value, gender) values ('nazista', 0);
insert into part3 (value, gender) values ('topzera', 0);
insert into part3 (value, gender) values ('normativa', 1);
insert into part3 (value, gender) values ('normativo', 2);
insert into part3 (value, gender) values ('chauvinista', 0);
insert into part3 (value, gender) values ('opressora', 1);
insert into part3 (value, gender) values ('opressor', 2);
insert into part3 (value, gender) values ('da islândia', 0);
insert into part3 (value, gender) values ('no box', 0);
insert into part3 (value, gender) values ('no freezer', 0);
insert into part3 (value, gender) values ('de iphone', 0);
insert into part3 (value, gender) values ('que fala "todes"', 0);
insert into part3 (value, gender) values ('que vive falando de boca cheia', 0);
insert into part3 (value, gender) values ('intrusiva', 1);
insert into part3 (value, gender) values ('intrusivo', 2);
insert into part3 (value, gender) values ('sarnenta', 1);
insert into part3 (value, gender) values ('sarnento', 2);
insert into part3 (value, gender) values ('bilili', 0);
insert into part3 (value, gender) values ('esganiçada', 1);
insert into part3 (value, gender) values ('esganiçado', 2);
insert into part3 (value, gender) values ('do pau de pau', 0);
insert into part3 (value, gender) values ('com 90% em MGLU3', 0);
insert into part3 (value, gender) values ('abusiva', 1);
insert into part3 (value, gender) values ('abusivo', 2);
insert into part3 (value, gender) values ('de cogumelos', 0);

-- 2022-06-16
insert into part0 (value, gender) values ('comedora de', 1);
insert into part0 (value, gender) values ('comedor de', 2);
insert into part0 (value, gender) values ('só fala de', 0);
insert into part0 (value, gender) values ('ovo de', 0);
insert into part0 (value, gender) values ('ova de', 0);
insert into part0 (value, gender) values ('fruto de', 0);
insert into part0 (value, gender) values ('fruta de', 0);
insert into part0 (value, gender) values ('frutinha de', 0);
insert into part0 (value, gender) values ('enfeite de', 0);
insert into part0 (value, gender) values ('imitação de', 0);
insert into part0 (value, gender) values ('descendente de', 0);
insert into part0 (value, gender) values ('ascendente de', 0);
insert into part0 (value, gender) values ('fala com a minha mão', 0);
insert into part0 (value, gender) values ('geração', 0);
insert into part0 (value, gender) values ('demarcação de', 0);
insert into part0 (value, gender) values ('rolha de', 0);
insert into part0 (value, gender) values ('tampa de', 0);
insert into part0 (value, gender) values ('não acerta uma', 1);
insert into part0 (value, gender) values ('não acerta um', 2);
insert into part0 (value, gender) values ('tocadora de', 1);
insert into part0 (value, gender) values ('tocador de', 2);
insert into part0 (value, gender) values ('prendedora de', 1);
insert into part0 (value, gender) values ('prendedor de', 2);
insert into part0 (value, gender) values ('detentora de', 1);
insert into part0 (value, gender) values ('detentor de', 2);
insert into part0 (value, gender) values ('defensora de', 1);
insert into part0 (value, gender) values ('defensor de', 2);
insert into part0 (value, gender) values ('gosto de', 0);
insert into part0 (value, gender) values ('vendedora de', 1);
insert into part0 (value, gender) values ('vendedor de', 2);
insert into part0 (value, gender) values ('plano de', 0);

insert into part1 (value, gender) values ('marmelada', 1);
insert into part1 (value, gender) values ('direita', 1);
insert into part1 (value, gender) values ('direito', 2);
insert into part1 (value, gender) values ('ocarina', 1);
insert into part1 (value, gender) values ('harpa', 1);
insert into part1 (value, gender) values ('cravo', 2);
insert into part1 (value, gender) values ('gaita', 1);
insert into part1 (value, gender) values ('gata', 1);
insert into part1 (value, gender) values ('gato', 2);
insert into part1 (value, gender) values ('madeira', 1);
insert into part1 (value, gender) values ('metrônomo', 2);
insert into part1 (value, gender) values ('pinóia', 1);
insert into part1 (value, gender) values ('flauta', 1);
insert into part1 (value, gender) values ('escorpião', 2);
insert into part1 (value, gender) values ('reclamão', 2);

insert into part2 (value, gender) values ('humana', 1);
insert into part2 (value, gender) values ('humano', 2);
insert into part2 (value, gender) values ('de fole', 0);
insert into part2 (value, gender) values ('descolorida', 1);
insert into part2 (value, gender) values ('descolorido', 2);
insert into part2 (value, gender) values ('sem cor', 0);
insert into part2 (value, gender) values ('preta', 1);
insert into part2 (value, gender) values ('preto', 2);
insert into part2 (value, gender) values ('na metanoia', 0);
insert into part2 (value, gender) values ('noiada', 1);
insert into part2 (value, gender) values ('noiado', 2);
insert into part2 (value, gender) values ('cantarolando', 0);
insert into part2 (value, gender) values ('flatulante', 0);
insert into part2 (value, gender) values ('ancorada', 1);
insert into part2 (value, gender) values ('ancorado', 2);
insert into part2 (value, gender) values ('acorrentada', 1);
insert into part2 (value, gender) values ('acorrentado', 2);
insert into part2 (value, gender) values ('miando', 0);
insert into part2 (value, gender) values ('drogada', 1);
insert into part2 (value, gender) values ('drogado', 2);

insert into part3 (value, gender) values ('de mana', 1);
insert into part3 (value, gender) values ('de mano', 2);
insert into part3 (value, gender) values ('dos manos', 0);
insert into part3 (value, gender) values ('no rolê', 0);
insert into part3 (value, gender) values ('sem rítmo', 0);
insert into part3 (value, gender) values ('descoordenada', 1);
insert into part3 (value, gender) values ('descoordenado', 2);
insert into part3 (value, gender) values ('destampada', 0);
insert into part3 (value, gender) values ('sem tampa', 0);
insert into part3 (value, gender) values ('copiona', 1);
insert into part3 (value, gender) values ('copião', 2);
insert into part3 (value, gender) values ('que fala com a mão', 0);
insert into part3 (value, gender) values ('no fundo do poço', 0);
insert into part3 (value, gender) values ('gritando gerônimo', 0);