create table part1 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

create table part2 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

create table part3 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

insert into part1 (value, gender) values ('tororó', 0);
insert into part1 (value, gender) values ('manequim', 0);
insert into part1 (value, gender) values ('pikachu', 0);
insert into part1 (value, gender) values ('filhote tartaruga', 0);

insert into part1 (value, gender) values ('sua bola', 1);
insert into part1 (value, gender) values ('sua mula', 1);
insert into part1 (value, gender) values ('sua égua', 1);
insert into part1 (value, gender) values ('filho duma girafa', 1);
insert into part1 (value, gender) values ('sua pamonha', 1);
insert into part1 (value, gender) values ('sua múmia', 1);
insert into part1 (value, gender) values ('sua cadeira', 1);
insert into part1 (value, gender) values ('ratazana', 1);
insert into part1 (value, gender) values ('barata', 1);
insert into part1 (value, gender) values ('batata', 1);
insert into part1 (value, gender) values ('lua', 1);
insert into part1 (value, gender) values ('meia', 1);
insert into part1 (value, gender) values ('vespa', 1);
insert into part1 (value, gender) values ('cobra', 1);
insert into part1 (value, gender) values ('sua pokébola', 1);
insert into part1 (value, gender) values ('sua anta', 1);
insert into part1 (value, gender) values ('ova de magikarp', 1);
insert into part1 (value, gender) values ('sua pedra', 1);
insert into part1 (value, gender) values ('êê tartaruga ninja', 1);
insert into part1 (value, gender) values ('sua pipa', 1);
insert into part1 (value, gender) values ('sua bananinha', 1);
insert into part1 (value, gender) values ('sua banana', 1);
insert into part1 (value, gender) values ('galinha pintadinha', 1);
insert into part1 (value, gender) values ('sua sereia fora dágua', 1);
insert into part1 (value, gender) values ('paçoca', 1);
insert into part1 (value, gender) values ('fruto de gambiarra', 1);
insert into part1 (value, gender) values ('fruto do mar', 2);
insert into part1 (value, gender) values ('ser marítimo', 2);
insert into part1 (value, gender) values ('cavalo marinho', 2);
insert into part1 (value, gender) values ('pinguim', 0);
insert into part1 (value, gender) values ('sua pipoqueira', 1);
insert into part1 (value, gender) values ('seu pipoqueiro', 1);
insert into part1 (value, gender) values ('sua bêbada', 1);
insert into part1 (value, gender) values ('seu bêbado', 2);

insert into part1 (value, gender) values ('esqueleto', 2);
insert into part1 (value, gender) values ('seu picolé', 2);
insert into part1 (value, gender) values ('seu cone', 2);
insert into part1 (value, gender) values ('seu ornitorrinco', 2);
insert into part1 (value, gender) values ('seu porco espinho', 2);
insert into part1 (value, gender) values ('seu pickles', 2);
insert into part1 (value, gender) values ('seu diabo', 2);
insert into part1 (value, gender) values ('seu peixe', 2);
insert into part1 (value, gender) values ('enfeite de oferenda', 2);
insert into part1 (value, gender) values ('enfeite de presente', 2);
insert into part1 (value, gender) values ('enfeite de arroz', 2);
insert into part1 (value, gender) values ('seu defunto', 2);
insert into part1 (value, gender) values ('seu caralho', 2);
insert into part1 (value, gender) values ('seu filhote de rato', 2);
insert into part1 (value, gender) values ('seu pokémon', 2);

-- part 2
insert into part2 (value, gender) values ('de bolinhas', 0);
insert into part2 (value, gender) values ('manco', 2);
insert into part2 (value, gender) values ('manca', 1);
insert into part2 (value, gender) values ('molhado', 2);
insert into part2 (value, gender) values ('molhada', 1);
insert into part2 (value, gender) values ('prematura', 1);
insert into part2 (value, gender) values ('prematuro', 2);
insert into part2 (value, gender) values ('hipnotizada', 1);
insert into part2 (value, gender) values ('hipnotizado', 2);
insert into part2 (value, gender) values ('mole', 0);
insert into part2 (value, gender) values ('de agulha', 0);
insert into part2 (value, gender) values ('molenga', 0);
insert into part2 (value, gender) values ('ambulante', 0);
insert into part2 (value, gender) values ('azul', 0);
insert into part2 (value, gender) values ('quadrada', 1);
insert into part2 (value, gender) values ('quadrado', 2);
insert into part2 (value, gender) values ('senoidal', 0);
insert into part2 (value, gender) values ('quebrada', 1);
insert into part2 (value, gender) values ('quebrado', 2);
insert into part2 (value, gender) values ('de jiló', 0);
insert into part2 (value, gender) values ('cara de mamão', 0);
insert into part2 (value, gender) values ('careca', 0);
insert into part2 (value, gender) values ('de rodinhas', 0);
insert into part2 (value, gender) values ('intragável', 0);
insert into part2 (value, gender) values ('bolha', 0);
insert into part2 (value, gender) values ('mal', 0);
insert into part2 (value, gender) values ('sem bago', 0);
insert into part2 (value, gender) values ('ululante', 0);
insert into part2 (value, gender) values ('furada', 1);
insert into part2 (value, gender) values ('furado', 2);
insert into part2 (value, gender) values ('marrom', 0);
insert into part2 (value, gender) values ('amassada', 1);
insert into part2 (value, gender) values ('amassado', 2);
insert into part2 (value, gender) values ('minguante', 0);
insert into part2 (value, gender) values ('cheia', 1);
insert into part2 (value, gender) values ('cheio', 2);
insert into part2 (value, gender) values ('elétrica', 1);
insert into part2 (value, gender) values ('elétrico', 2);
insert into part2 (value, gender) values ('sem rodinhas', 0);
insert into part2 (value, gender) values ('enferrujada', 1);
insert into part2 (value, gender) values ('enferrujado', 2);
insert into part2 (value, gender) values ('amarrada', 1);
insert into part2 (value, gender) values ('amarrado', 2);
insert into part2 (value, gender) values ('esverdeada', 1);
insert into part2 (value, gender) values ('esverdeado', 2);
insert into part2 (value, gender) values ('com gosto de salsicha', 0);
insert into part2 (value, gender) values ('animal', 0);
insert into part2 (value, gender) values ('do cabelo pixaim', 0);
insert into part2 (value, gender) values ('sem cabelo', 0);
insert into part2 (value, gender) values ('da montanha', 0);
insert into part2 (value, gender) values ('sem mochila', 0);
insert into part2 (value, gender) values ('suja', 1);
insert into part2 (value, gender) values ('sujo', 2);
insert into part2 (value, gender) values ('amarga', 1);
insert into part2 (value, gender) values ('amargo', 2);
insert into part2 (value, gender) values ('uvinha de mulher', 0);
insert into part2 (value, gender) values ('minecrafter', 0);
insert into part2 (value, gender) values ('de óculos', 0);
insert into part2 (value, gender) values ('sem óculos', 0);
insert into part2 (value, gender) values ('sem nariz', 0);
insert into part2 (value, gender) values ('sem maquiagem', 0);
insert into part2 (value, gender) values ('perdida', 1);
insert into part2 (value, gender) values ('perdido', 2);
insert into part2 (value, gender) values ('pif pif', 0);
insert into part2 (value, gender) values ('sem dedo', 0);
insert into part2 (value, gender) values ('cigana', 1);
insert into part2 (value, gender) values ('cigano', 2);

-- part 3
insert into part3 (value, gender) values ('amarela', 1);
insert into part3 (value, gender) values ('amarelo', 2);
insert into part3 (value, gender) values ('de taubaté', 0);
insert into part3 (value, gender) values ('bola bola', 0);
insert into part3 (value, gender) values ('gelada', 1);
insert into part3 (value, gender) values ('gelado', 2);
insert into part3 (value, gender) values ('sem dente', 0);
insert into part3 (value, gender) values ('vendedora de produtos jequiti', 1);
insert into part3 (value, gender) values ('vendedor da jequiti', 2);
insert into part3 (value, gender) values ('vendedora da avon', 1);
insert into part3 (value, gender) values ('vendedor da avon', 2);
insert into part3 (value, gender) values ('de raio laser', 0);
insert into part3 (value, gender) values ('mobile', 0);
insert into part3 (value, gender) values ('na noite', 0);
insert into part3 (value, gender) values ('noturna', 1);
insert into part3 (value, gender) values ('noturno', 2);
insert into part3 (value, gender) values ('parecida com o sonic', 1);
insert into part3 (value, gender) values ('parecido com o sonic', 2);
insert into part3 (value, gender) values ('de skate', 0);
insert into part3 (value, gender) values ('vermelha', 1);
insert into part3 (value, gender) values ('vermelho', 2);
insert into part3 (value, gender) values ('madura', 1);
insert into part3 (value, gender) values ('maduro', 2);
insert into part3 (value, gender) values ('sem mãe', 0);
insert into part3 (value, gender) values ('sem pau', 0);
insert into part3 (value, gender) values ('do pau', 0);
insert into part3 (value, gender) values ('incubada', 1);
insert into part3 (value, gender) values ('incubado', 2);
insert into part3 (value, gender) values ('no insulfilme', 0);
insert into part3 (value, gender) values ('vegana', 1);
insert into part3 (value, gender) values ('vegano', 2);
insert into part3 (value, gender) values ('vegetal', 0);
insert into part3 (value, gender) values ('com tomate seco', 0);
insert into part3 (value, gender) values ('parecida com a medusa', 1);
insert into part3 (value, gender) values ('parecido com a medusa', 2);
insert into part3 (value, gender) values ('perfurante', 0);
insert into part3 (value, gender) values ('voadora', 1);
insert into part3 (value, gender) values ('voador', 2);
insert into part3 (value, gender) values ('filhote de peppa pig', 0);
insert into part3 (value, gender) values ('jogadora de lol', 1);
insert into part3 (value, gender) values ('jogador de lol', 2);
insert into part3 (value, gender) values ('jogadora de minecraft', 1);
insert into part3 (value, gender) values ('jogador de minecraft', 2);
insert into part3 (value, gender) values ('no caixão', 0);
insert into part3 (value, gender) values ('sem caixão', 0);
insert into part3 (value, gender) values ('conservada', 1);
insert into part3 (value, gender) values ('conservado', 2);
insert into part3 (value, gender) values ('acabada', 1);
insert into part3 (value, gender) values ('acabado', 2);
insert into part3 (value, gender) values ('na superfície', 0);
insert into part3 (value, gender) values ('enterrada', 1);
insert into part3 (value, gender) values ('enterrado', 2);
insert into part3 (value, gender) values ('descascada', 1);
insert into part3 (value, gender) values ('descascado', 2);
insert into part3 (value, gender) values ('desencapada', 1);
insert into part3 (value, gender) values ('desencapado', 2);
insert into part3 (value, gender) values ('desenrolada', 1);
insert into part3 (value, gender) values ('desenrolado', 2);
insert into part3 (value, gender) values ('farpada', 1);
insert into part3 (value, gender) values ('farpado', 2);
insert into part3 (value, gender) values ('descalibrada', 1);
insert into part3 (value, gender) values ('descalibrado', 2);
insert into part3 (value, gender) values ('vazia', 1);
insert into part3 (value, gender) values ('vazio', 2);
insert into part3 (value, gender) values ('mal passada', 1);
insert into part3 (value, gender) values ('mal passado', 2);
insert into part3 (value, gender) values ('inacabada', 1);
insert into part3 (value, gender) values ('inacabado', 2);
insert into part3 (value, gender) values ('torta', 1);
insert into part3 (value, gender) values ('torto', 2);
insert into part3 (value, gender) values ('estraviada pelos correios', 1);
insert into part3 (value, gender) values ('estraviado pelos correios', 2);
insert into part3 (value, gender) values ('viajante', 0);
insert into part3 (value, gender) values ('congelada', 1);
insert into part3 (value, gender) values ('congelado', 2);
insert into part3 (value, gender) values ('desnutrida', 1);
insert into part3 (value, gender) values ('desnutrido', 2);
insert into part3 (value, gender) values ('polar', 0);
insert into part3 (value, gender) values ('mecânica', 1);
insert into part3 (value, gender) values ('mecânico', 2);
insert into part3 (value, gender) values ('desacoplada', 1);
insert into part3 (value, gender) values ('desacoplado', 2);
insert into part3 (value, gender) values ('marinha', 1);
insert into part3 (value, gender) values ('marinho', 2);
insert into part3 (value, gender) values ('terrestre', 0);
insert into part3 (value, gender) values ('aérea', 1);
insert into part3 (value, gender) values ('aéreo', 2);
insert into part3 (value, gender) values ('na autópsia', 0);
insert into part3 (value, gender) values ('da era feudal', 0);
insert into part3 (value, gender) values ('em 240p', 0);
insert into part3 (value, gender) values ('com gergelim', 0);
insert into part3 (value, gender) values ('meio amarga', 1);
insert into part3 (value, gender) values ('meio amargo', 2);
insert into part3 (value, gender) values ('parecida com o pikachu', 1);
insert into part3 (value, gender) values ('parecido com o pikachu', 2);
insert into part3 (value, gender) values ('deslizante', 0);

-- 2021-02-08
update part1 set value = 'ova de magikarp' where value = 'sua magikarp';
update part1 set value = 'tororó', gender = 0 where value = 'seu tororó';
update part1 set value = 'manequim', gender = 0 where value = 'seu manequim';
update part1 set value = 'pikachu', gender = 0 where value = 'seu pikachu';
update part1 set value = 'filhote de tartaruga', gender = 0 where value = 'sua tartaruga';

insert into part1 (value, gender) values ('filhote de quimera', 0);
insert into part1 (value, gender) values ('batata canoa', 1);
insert into part1 (value, gender) values ('baka', 0);
insert into part1 (value, gender) values ('otaku', 0);
insert into part1 (value, gender) values ('salgadinho', 2);
insert into part1 (value, gender) values ('que ameba', 1);
insert into part1 (value, gender) values ('seu marisco', 2);
insert into part1 (value, gender) values ('sua traveca', 1);
insert into part1 (value, gender) values ('seu traveco', 2);
insert into part1 (value, gender) values ('uvinha', 1);
insert into part1 (value, gender) values ('meu pau', 2);
insert into part1 (value, gender) values ('toalha', 1);
insert into part1 (value, gender) values ('sua pagodeira', 1);
insert into part1 (value, gender) values ('seu pagodeiro', 2);
insert into part1 (value, gender) values ('filha dum pagodeiro', 2);
insert into part1 (value, gender) values ('filho duma pagodeira', 0);
insert into part1 (value, gender) values ('piano desafinado', 2);
insert into part1 (value, gender) values ('participante do big brother', 0);
insert into part1 (value, gender) values ('mas que bagre', 2);
insert into part1 (value, gender) values ('que artista', 0);
insert into part1 (value, gender) values ('mas é um artista', 2);
insert into part1 (value, gender) values ('sua dízima periódica', 1);
insert into part1 (value, gender) values ('seu zero à esquerda', 2);
insert into part1 (value, gender) values ('ninho de formiga', 1);
insert into part1 (value, gender) values ('puta falta de sacanagem', 1);
insert into part1 (value, gender) values ('seu patê', 2);
insert into part1 (value, gender) values ('seu fatality', 2);
insert into part1 (value, gender) values ('letreiro', 2);
insert into part1 (value, gender) values ('seu boneco assassino', 2);
insert into part1 (value, gender) values ('sua buceta', 1);
insert into part1 (value, gender) values ('mas é um caralho', 2);
insert into part1 (value, gender) values ('sua besta', 1);
insert into part1 (value, gender) values ('seu besta', 2);
insert into part1 (value, gender) values ('caçadora de giromba', 1);
insert into part1 (value, gender) values ('caçador de giromba', 2);
insert into part1 (value, gender) values ('mas que desgraça', 1);
insert into part1 (value, gender) values ('era só o que me faltava nessa bosta', 1);
insert into part1 (value, gender) values ('era o que me faltava nesse caralho', 2);
insert into part1 (value, gender) values ('que vida', 1);
insert into part1 (value, gender) values ('meu cu', 2);
insert into part1 (value, gender) values ('seu cu', 2);
insert into part1 (value, gender) values ('seu t-rex', 2);
insert into part1 (value, gender) values ('seu pterodáctilo', 2);

insert into part2 (value, gender) values ('parecido com o jason', 2);
insert into part2 (value, gender) values ('luminosa', 1);
insert into part2 (value, gender) values ('luminoso', 2);
insert into part2 (value, gender) values ('refutada', 1);
insert into part2 (value, gender) values ('refutado', 2);
insert into part2 (value, gender) values ('globalista', 0);
insert into part2 (value, gender) values ('terraplanista', 0);
insert into part2 (value, gender) values ('sem vírgula', 0);
insert into part2 (value, gender) values ('desmilinguida', 1);
insert into part2 (value, gender) values ('desmilinguido', 2);
insert into part2 (value, gender) values ('dissolvida', 1);
insert into part2 (value, gender) values ('dissolvido', 2);
insert into part2 (value, gender) values ('safada', 1);
insert into part2 (value, gender) values ('safado', 2);
insert into part2 (value, gender) values ('esfacelada', 1);
insert into part2 (value, gender) values ('esfacelado', 2);
insert into part2 (value, gender) values ('sem sal', 0);
insert into part2 (value, gender) values ('espongiforme', 0);
insert into part2 (value, gender) values ('estranha', 1);
insert into part2 (value, gender) values ('estranho', 2);
insert into part2 (value, gender) values ('cabeluda', 1);
insert into part2 (value, gender) values ('cabeludo', 2);
insert into part2 (value, gender) values ('de salto alto', 0);
insert into part2 (value, gender) values ('travestida de barbie', 1);
insert into part2 (value, gender) values ('travestido de urso', 2);
insert into part2 (value, gender) values ('dura', 1);
insert into part2 (value, gender) values ('duro', 2);
insert into part2 (value, gender) values ('mal feita', 1);
insert into part2 (value, gender) values ('mal feito', 2);
insert into part2 (value, gender) values ('panificada', 1);
insert into part2 (value, gender) values ('panificado', 2);
insert into part2 (value, gender) values ('ensaboada', 1);
insert into part2 (value, gender) values ('ensaboado', 2);
insert into part2 (value, gender) values ('barroca', 1);
insert into part2 (value, gender) values ('barroco', 2);
insert into part2 (value, gender) values ('assombrada', 1);
insert into part2 (value, gender) values ('assombrado', 2);
insert into part2 (value, gender) values ('surfista', 0);
insert into part2 (value, gender) values ('programador de php', 2);
insert into part2 (value, gender) values ('programadora de php', 2);
insert into part2 (value, gender) values ('desajustada', 1);
insert into part2 (value, gender) values ('desajustado', 2);
insert into part2 (value, gender) values ('saltitante', 0);
insert into part2 (value, gender) values ('grávida', 1);
insert into part2 (value, gender) values ('grávido', 2);
insert into part2 (value, gender) values ('de abobrinha', 0);
insert into part2 (value, gender) values ('de chuchu', 0);
insert into part2 (value, gender) values ('desqualificada', 1);
insert into part2 (value, gender) values ('desqualificado', 2);
insert into part2 (value, gender) values ('tarada', 1);
insert into part2 (value, gender) values ('tarado', 2);
insert into part2 (value, gender) values ('engasgada', 1);
insert into part2 (value, gender) values ('engasgado', 2);
insert into part2 (value, gender) values ('pole dancer', 0);
insert into part2 (value, gender) values ('desnorteada', 1);
insert into part2 (value, gender) values ('desnorteado', 2);
insert into part2 (value, gender) values ('passeando de crocs', 0);
insert into part2 (value, gender) values ('que desfila de crocs', 0);
insert into part2 (value, gender) values ('desfilando', 0);
insert into part2 (value, gender) values ('profunda', 1);
insert into part2 (value, gender) values ('profundo', 2);
insert into part2 (value, gender) values ('veiuda', 1);
insert into part2 (value, gender) values ('veiudo', 2);
insert into part2 (value, gender) values ('velha', 1);
insert into part2 (value, gender) values ('velho', 2);
insert into part2 (value, gender) values ('com gosto de peixe', 0);
insert into part2 (value, gender) values ('envelhecida', 1);
insert into part2 (value, gender) values ('envelhecido', 2);
insert into part2 (value, gender) values ('cachaceira', 1);
insert into part2 (value, gender) values ('cachaceiro', 2);
insert into part2 (value, gender) values ('bombada', 1);
insert into part2 (value, gender) values ('bombado', 2);
insert into part2 (value, gender) values ('de nadadeiras', 0);
insert into part2 (value, gender) values ('antagonista', 0);
insert into part2 (value, gender) values ('maníaca', 1);
insert into part2 (value, gender) values ('maníaco', 2);
insert into part2 (value, gender) values ('sedentária', 1);
insert into part2 (value, gender) values ('sedentário', 2);
insert into part2 (value, gender) values ('absolutamente', 0);
insert into part2 (value, gender) values ('oriunda do mar', 1);
insert into part2 (value, gender) values ('vindo do mar', 2);
insert into part2 (value, gender) values ('palpiteira', 1);
insert into part2 (value, gender) values ('palpiteiro', 2);
insert into part2 (value, gender) values ('ensanguentada', 1);
insert into part2 (value, gender) values ('ensanguentado', 2);
insert into part2 (value, gender) values ('maluca', 1);
insert into part2 (value, gender) values ('maluco', 2);
insert into part2 (value, gender) values ('com chapéu de alumínio', 0);
insert into part2 (value, gender) values ('folclórica', 1);
insert into part2 (value, gender) values ('folclórico', 2);
insert into part2 (value, gender) values ('alegórica', 1);
insert into part2 (value, gender) values ('alegórico', 2);
insert into part2 (value, gender) values ('hipocondríaca', 1);
insert into part2 (value, gender) values ('hipocondríaco', 2);
insert into part2 (value, gender) values ('figurante', 0);
insert into part2 (value, gender) values ('terrorista', 0);

insert into part3 (value, gender) values ('da calça quadrada', 0);
insert into part3 (value, gender) values ('parecendo uma amoeba', 0);
insert into part3 (value, gender) values ('amolecida', 1);
insert into part3 (value, gender) values ('amolecido', 2);
insert into part3 (value, gender) values ('global', 0);
insert into part3 (value, gender) values ('no ácido sulfúrico', 0);
insert into part3 (value, gender) values ('suspensa no ar', 1);
insert into part3 (value, gender) values ('suspenso no ar', 2);
insert into part3 (value, gender) values ('mastigada por um urso', 1);
insert into part3 (value, gender) values ('mastigado por uma ursinha', 2);
insert into part3 (value, gender) values ('pifada', 1);
insert into part3 (value, gender) values ('pifado', 2);
insert into part3 (value, gender) values ('sem tempero', 0);
insert into part3 (value, gender) values ('destemperada', 1);
insert into part3 (value, gender) values ('destemperado', 2);
insert into part3 (value, gender) values ('descabelada', 1);
insert into part3 (value, gender) values ('descabelado', 2);
insert into part3 (value, gender) values ('e malformada', 1);
insert into part3 (value, gender) values ('e malformado', 2);
insert into part3 (value, gender) values ('mal criada', 1);
insert into part3 (value, gender) values ('mal criado', 2);
insert into part3 (value, gender) values ('com cara de acidente de trem', 0);
insert into part3 (value, gender) values ('que parece a samara', 0);
insert into part3 (value, gender) values ('cancelada pela globo', 1);
insert into part3 (value, gender) values ('cancelado pelo sbt', 2);
insert into part3 (value, gender) values ('tendendo ao infinito', 0);
insert into part3 (value, gender) values ('da casca assombrosa', 1);
insert into part3 (value, gender) values ('do casco assombroso', 2);
insert into part3 (value, gender) values ('sem casaco', 0);
insert into part3 (value, gender) values ('com cara de silverfish', 0);
insert into part3 (value, gender) values ('sem bunda', 0);
insert into part3 (value, gender) values ('no mastro', 0);
insert into part3 (value, gender) values ('num objeto fálico', 0);
insert into part3 (value, gender) values ('sem calcinha', 0);
insert into part3 (value, gender) values ('de calcinha', 0);
insert into part3 (value, gender) values ('que xinga muito no twitter', 0);
insert into part3 (value, gender) values ('no desfiladeiro', 0);
insert into part3 (value, gender) values ('na beira do abismo', 0);
insert into part3 (value, gender) values ('da beira do abismo', 0);
insert into part3 (value, gender) values ('no penhasco', 0);
insert into part3 (value, gender) values ('mucha', 1);
insert into part3 (value, gender) values ('mucho', 2);
insert into part3 (value, gender) values ('podre', 0);
insert into part3 (value, gender) values ('fedida', 1);
insert into part3 (value, gender) values ('fedido', 2);
insert into part3 (value, gender) values ('no carvalho', 0);
insert into part3 (value, gender) values ('no barril', 0);
insert into part3 (value, gender) values ('apreciadora de paratudo', 1);
insert into part3 (value, gender) values ('degustador de paratudo', 2);
insert into part3 (value, gender) values ('sem cérebro', 0);
insert into part3 (value, gender) values ('acéfala', 1);
insert into part3 (value, gender) values ('acéfalo', 2);
insert into part3 (value, gender) values ('no lixo', 0);
insert into part3 (value, gender) values ('onomatopeica', 1);
insert into part3 (value, gender) values ('onomatopeico', 2);
insert into part3 (value, gender) values ('deserdada pela rainha', 1);
insert into part3 (value, gender) values ('deserdado pela rainha', 2);
insert into part3 (value, gender) values ('pra cacete', 0);
insert into part3 (value, gender) values ('para um caralho', 0);
insert into part3 (value, gender) values ('num navio cargueiro', 0);
insert into part3 (value, gender) values ('desfigurada', 1);
insert into part3 (value, gender) values ('desfigurado', 2);
insert into part3 (value, gender) values ('numa sexta feira 13', 0);
insert into part3 (value, gender) values ('esmagada por um titã de anômalo', 1);
insert into part3 (value, gender) values ('esmagado por um titã bestial', 2);
insert into part3 (value, gender) values ('que parece que já morreu', 0);
insert into part3 (value, gender) values ('fingindo de morta', 1);
insert into part3 (value, gender) values ('com cara de morto', 2);
insert into part3 (value, gender) values ('conspiracionista', 0);
insert into part3 (value, gender) values ('de perna aberta', 0);
insert into part3 (value, gender) values ('sem perna', 0);
insert into part3 (value, gender) values ('em cima do muro', 0);
insert into part3 (value, gender) values ('da novela das 8', 0);
insert into part3 (value, gender) values ('de novela mexicana', 0);
insert into part3 (value, gender) values ('de dorama coreano', 0);
insert into part3 (value, gender) values ('depois da explosão', 0);
insert into part3 (value, gender) values ('do braço curto', 0);
insert into part3 (value, gender) values ('louca de pó', 1);
insert into part3 (value, gender) values ('virado no pó', 2);
insert into part3 (value, gender) values ('maconheira', 1);
insert into part3 (value, gender) values ('maconheiro', 2);