create table part0 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

create table part1 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

create table part2 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

create table part3 (
    id serial PRIMARY KEY,
    value text unique not null,
    gender integer,
    lang integer not null default 0,
    created timestamp not null default now()
);

insert into part1 (value, gender) values ('tororó', 0);
insert into part1 (value, gender) values ('manequim', 0);
insert into part1 (value, gender) values ('pikachu', 0);
insert into part1 (value, gender) values ('filhote tartaruga', 0);

insert into part1 (value, gender) values ('bola', 1);
insert into part1 (value, gender) values ('mula', 1);
insert into part1 (value, gender) values ('égua', 1);
insert into part1 (value, gender) values ('girafa', 1);
insert into part1 (value, gender) values ('pamonha', 1);
insert into part1 (value, gender) values ('múmia', 1);
insert into part1 (value, gender) values ('cadeira', 1);
insert into part1 (value, gender) values ('ratazana', 1);
insert into part1 (value, gender) values ('barata', 1);
insert into part1 (value, gender) values ('batata', 1);
insert into part1 (value, gender) values ('lua', 1);
insert into part1 (value, gender) values ('meia', 1);
insert into part1 (value, gender) values ('vespa', 1);
insert into part1 (value, gender) values ('cobra', 1);
insert into part1 (value, gender) values ('pokébola', 1);
insert into part1 (value, gender) values ('anta', 1);
insert into part1 (value, gender) values ('ova de magikarp', 1);
insert into part1 (value, gender) values ('pedra', 1);
insert into part1 (value, gender) values ('tartaruga ninja', 1);
insert into part1 (value, gender) values ('pipa', 1);
insert into part1 (value, gender) values ('bananinha', 1);
insert into part1 (value, gender) values ('banana', 1);
insert into part1 (value, gender) values ('galinha pintadinha', 1);
insert into part1 (value, gender) values ('sereia fora dágua', 1);
insert into part1 (value, gender) values ('paçoca', 1);
insert into part1 (value, gender) values ('fruto de gambiarra', 1);
insert into part1 (value, gender) values ('fruto do mar', 2);
insert into part1 (value, gender) values ('ser marítimo', 2);
insert into part1 (value, gender) values ('cavalo marinho', 2);
insert into part1 (value, gender) values ('pinguim', 0);
insert into part1 (value, gender) values ('pipoqueira', 1);
insert into part1 (value, gender) values ('pipoqueiro', 1);
insert into part1 (value, gender) values ('bêbada', 1);
insert into part1 (value, gender) values ('bêbado', 2);
insert into part1 (value, gender) values ('queimada', 1);
insert into part1 (value, gender) values ('queimado', 2);

insert into part1 (value, gender) values ('esqueleto', 2);
insert into part1 (value, gender) values ('picolé', 2);
insert into part1 (value, gender) values ('cone', 2);
insert into part1 (value, gender) values ('ornitorrinco', 2);
insert into part1 (value, gender) values ('porco espinho', 2);
insert into part1 (value, gender) values ('pickles', 2);
insert into part1 (value, gender) values ('diabo', 2);
insert into part1 (value, gender) values ('peixe', 2);
insert into part1 (value, gender) values ('enfeite de oferenda', 2);
insert into part1 (value, gender) values ('enfeite de presente', 2);
insert into part1 (value, gender) values ('enfeite de arroz', 2);
insert into part1 (value, gender) values ('defunto', 2);
insert into part1 (value, gender) values ('filhote de rato', 2);
insert into part1 (value, gender) values ('pokémon', 2);

-- part 2
insert into part2 (value, gender) values ('de bolinhas', 0);
insert into part2 (value, gender) values ('bugada', 1);
insert into part2 (value, gender) values ('bugado', 2);
insert into part2 (value, gender) values ('manco', 2);
insert into part2 (value, gender) values ('manca', 1);
insert into part2 (value, gender) values ('molhado', 2);
insert into part2 (value, gender) values ('molhada', 1);
insert into part2 (value, gender) values ('prematura', 1);
insert into part2 (value, gender) values ('prematuro', 2);
insert into part2 (value, gender) values ('hipnotizada', 1);
insert into part2 (value, gender) values ('hipnotizado', 2);
insert into part2 (value, gender) values ('mole', 0);
insert into part2 (value, gender) values ('de agulha', 0);
insert into part2 (value, gender) values ('molenga', 0);
insert into part2 (value, gender) values ('ambulante', 0);
insert into part2 (value, gender) values ('azul', 0);
insert into part2 (value, gender) values ('quadrada', 1);
insert into part2 (value, gender) values ('quadrado', 2);
insert into part2 (value, gender) values ('senoidal', 0);
insert into part2 (value, gender) values ('quebrada', 1);
insert into part2 (value, gender) values ('quebrado', 2);
insert into part2 (value, gender) values ('de jiló', 0);
insert into part2 (value, gender) values ('cara de mamão', 0);
insert into part2 (value, gender) values ('careca', 0);
insert into part2 (value, gender) values ('de rodinhas', 0);
insert into part2 (value, gender) values ('intragável', 0);
insert into part2 (value, gender) values ('bolha', 0);
insert into part2 (value, gender) values ('mal', 0);
insert into part2 (value, gender) values ('sem bago', 0);
insert into part2 (value, gender) values ('ululante', 0);
insert into part2 (value, gender) values ('furada', 1);
insert into part2 (value, gender) values ('furado', 2);
insert into part2 (value, gender) values ('marrom', 0);
insert into part2 (value, gender) values ('amassada', 1);
insert into part2 (value, gender) values ('amassado', 2);
insert into part2 (value, gender) values ('minguante', 0);
insert into part2 (value, gender) values ('cheia', 1);
insert into part2 (value, gender) values ('cheio', 2);
insert into part2 (value, gender) values ('elétrica', 1);
insert into part2 (value, gender) values ('elétrico', 2);
insert into part2 (value, gender) values ('sem rodinhas', 0);
insert into part2 (value, gender) values ('enferrujada', 1);
insert into part2 (value, gender) values ('enferrujado', 2);
insert into part2 (value, gender) values ('amarrada', 1);
insert into part2 (value, gender) values ('amarrado', 2);
insert into part2 (value, gender) values ('esverdeada', 1);
insert into part2 (value, gender) values ('esverdeado', 2);
insert into part2 (value, gender) values ('com gosto de salsicha', 0);
insert into part2 (value, gender) values ('animal', 0);
insert into part2 (value, gender) values ('do cabelo pixaim', 0);
insert into part2 (value, gender) values ('sem cabelo', 0);
insert into part2 (value, gender) values ('da montanha', 0);
insert into part2 (value, gender) values ('sem mochila', 0);
insert into part2 (value, gender) values ('suja', 1);
insert into part2 (value, gender) values ('sujo', 2);
insert into part2 (value, gender) values ('amarga', 1);
insert into part2 (value, gender) values ('amargo', 2);
insert into part2 (value, gender) values ('uvinha de mulher', 0);
insert into part2 (value, gender) values ('minecrafter', 0);
insert into part2 (value, gender) values ('de óculos', 0);
insert into part2 (value, gender) values ('sem óculos', 0);
insert into part2 (value, gender) values ('sem nariz', 0);
insert into part2 (value, gender) values ('sem maquiagem', 0);
insert into part2 (value, gender) values ('perdida', 1);
insert into part2 (value, gender) values ('perdido', 2);
insert into part2 (value, gender) values ('pif pif', 0);
insert into part2 (value, gender) values ('sem dedo', 0);
insert into part2 (value, gender) values ('cigana', 1);
insert into part2 (value, gender) values ('cigano', 2);

-- part 3
insert into part3 (value, gender) values ('amarela', 1);
insert into part3 (value, gender) values ('amarelo', 2);
insert into part3 (value, gender) values ('de taubaté', 0);
insert into part3 (value, gender) values ('bola bola', 0);
insert into part3 (value, gender) values ('gelada', 1);
insert into part3 (value, gender) values ('gelado', 2);
insert into part3 (value, gender) values ('sem dente', 0);
insert into part3 (value, gender) values ('vendedora de produtos jequiti', 1);
insert into part3 (value, gender) values ('vendedor da jequiti', 2);
insert into part3 (value, gender) values ('vendedora da avon', 1);
insert into part3 (value, gender) values ('vendedor da avon', 2);
insert into part3 (value, gender) values ('de raio laser', 0);
insert into part3 (value, gender) values ('mobile', 0);
insert into part3 (value, gender) values ('na noite', 0);
insert into part3 (value, gender) values ('noturna', 1);
insert into part3 (value, gender) values ('noturno', 2);
insert into part3 (value, gender) values ('parecida com o sonic', 1);
insert into part3 (value, gender) values ('parecido com o sonic', 2);
insert into part3 (value, gender) values ('de skate', 0);
insert into part3 (value, gender) values ('vermelha', 1);
insert into part3 (value, gender) values ('vermelho', 2);
insert into part3 (value, gender) values ('madura', 1);
insert into part3 (value, gender) values ('maduro', 2);
insert into part3 (value, gender) values ('sem mãe', 0);
insert into part3 (value, gender) values ('sem pau', 0);
insert into part3 (value, gender) values ('do pau', 0);
insert into part3 (value, gender) values ('incubada', 1);
insert into part3 (value, gender) values ('incubado', 2);
insert into part3 (value, gender) values ('no insulfilme', 0);
insert into part3 (value, gender) values ('vegana', 1);
insert into part3 (value, gender) values ('vegano', 2);
insert into part3 (value, gender) values ('vegetal', 0);
insert into part3 (value, gender) values ('com tomate seco', 0);
insert into part3 (value, gender) values ('parecida com a medusa', 1);
insert into part3 (value, gender) values ('parecido com a medusa', 2);
insert into part3 (value, gender) values ('perfurante', 0);
insert into part3 (value, gender) values ('voadora', 1);
insert into part3 (value, gender) values ('voador', 2);
insert into part3 (value, gender) values ('filhote de peppa pig', 0);
insert into part3 (value, gender) values ('jogadora de lol', 1);
insert into part3 (value, gender) values ('jogador de lol', 2);
insert into part3 (value, gender) values ('jogadora de minecraft', 1);
insert into part3 (value, gender) values ('jogador de minecraft', 2);
insert into part3 (value, gender) values ('no caixão', 0);
insert into part3 (value, gender) values ('sem caixão', 0);
insert into part3 (value, gender) values ('conservada', 1);
insert into part3 (value, gender) values ('conservado', 2);
insert into part3 (value, gender) values ('acabada', 1);
insert into part3 (value, gender) values ('acabado', 2);
insert into part3 (value, gender) values ('na superfície', 0);
insert into part3 (value, gender) values ('enterrada', 1);
insert into part3 (value, gender) values ('enterrado', 2);
insert into part3 (value, gender) values ('descascada', 1);
insert into part3 (value, gender) values ('descascado', 2);
insert into part3 (value, gender) values ('desencapada', 1);
insert into part3 (value, gender) values ('desencapado', 2);
insert into part3 (value, gender) values ('desenrolada', 1);
insert into part3 (value, gender) values ('desenrolado', 2);
insert into part3 (value, gender) values ('farpada', 1);
insert into part3 (value, gender) values ('farpado', 2);
insert into part3 (value, gender) values ('descalibrada', 1);
insert into part3 (value, gender) values ('descalibrado', 2);
insert into part3 (value, gender) values ('vazia', 1);
insert into part3 (value, gender) values ('vazio', 2);
insert into part3 (value, gender) values ('mal passada', 1);
insert into part3 (value, gender) values ('mal passado', 2);
insert into part3 (value, gender) values ('inacabada', 1);
insert into part3 (value, gender) values ('inacabado', 2);
insert into part3 (value, gender) values ('torta', 1);
insert into part3 (value, gender) values ('torto', 2);
insert into part3 (value, gender) values ('estraviada pelos correios', 1);
insert into part3 (value, gender) values ('estraviado pelos correios', 2);
insert into part3 (value, gender) values ('viajante', 0);
insert into part3 (value, gender) values ('congelada', 1);
insert into part3 (value, gender) values ('congelado', 2);
insert into part3 (value, gender) values ('desnutrida', 1);
insert into part3 (value, gender) values ('desnutrido', 2);
insert into part3 (value, gender) values ('polar', 0);
insert into part3 (value, gender) values ('mecânica', 1);
insert into part3 (value, gender) values ('mecânico', 2);
insert into part3 (value, gender) values ('desacoplada', 1);
insert into part3 (value, gender) values ('desacoplado', 2);
insert into part3 (value, gender) values ('marinha', 1);
insert into part3 (value, gender) values ('marinho', 2);
insert into part3 (value, gender) values ('terrestre', 0);
insert into part3 (value, gender) values ('aérea', 1);
insert into part3 (value, gender) values ('aéreo', 2);
insert into part3 (value, gender) values ('na autópsia', 0);
insert into part3 (value, gender) values ('da era feudal', 0);
insert into part3 (value, gender) values ('em 240p', 0);
insert into part3 (value, gender) values ('com gergelim', 0);
insert into part3 (value, gender) values ('meio amarga', 1);
insert into part3 (value, gender) values ('meio amargo', 2);
insert into part3 (value, gender) values ('parecida com o pikachu', 1);
insert into part3 (value, gender) values ('parecido com o pikachu', 2);
insert into part3 (value, gender) values ('deslizante', 0);

-- 2021-02-08
update part1 set value = 'ova de magikarp' where value = 'sua magikarp';
update part1 set value = 'tororó', gender = 0 where value = 'seu tororó';
update part1 set value = 'manequim', gender = 0 where value = 'seu manequim';
update part1 set value = 'pikachu', gender = 0 where value = 'seu pikachu';
update part1 set value = 'filhote de tartaruga', gender = 0 where value = 'sua tartaruga';

insert into part1 (value, gender) values ('quimera', 0);
insert into part1 (value, gender) values ('batata canoa', 1);
insert into part1 (value, gender) values ('baka', 0);
insert into part1 (value, gender) values ('salgadinho', 2);
insert into part1 (value, gender) values ('ameba', 1);
insert into part1 (value, gender) values ('marisco', 2);
insert into part1 (value, gender) values ('traveca', 1);
insert into part1 (value, gender) values ('traveco', 2);
insert into part1 (value, gender) values ('uvinha', 1);
insert into part1 (value, gender) values ('pau', 2);
insert into part1 (value, gender) values ('toalha', 1);
insert into part1 (value, gender) values ('pagodeira', 1);
insert into part1 (value, gender) values ('pagodeiro', 2);
insert into part1 (value, gender) values ('piano desafinado', 2);
insert into part1 (value, gender) values ('participante do big brother', 0);
insert into part1 (value, gender) values ('bagre', 2);
insert into part1 (value, gender) values ('artista', 0);
insert into part1 (value, gender) values ('dízima periódica', 1);
insert into part1 (value, gender) values ('zero à esquerda', 2);
insert into part1 (value, gender) values ('formiga', 1);
insert into part1 (value, gender) values ('falta de sacanagem', 1);
insert into part1 (value, gender) values ('patê', 2);
insert into part1 (value, gender) values ('fatality', 2);
insert into part1 (value, gender) values ('letreiro', 2);
insert into part1 (value, gender) values ('boneco assassino', 2);
insert into part1 (value, gender) values ('besta', 1);
insert into part1 (value, gender) values ('giromba', 1);
insert into part1 (value, gender) values ('desgraça', 1);
insert into part1 (value, gender) values ('bosta', 1);
insert into part1 (value, gender) values ('vida', 1);
insert into part1 (value, gender) values ('t-rex', 2);
insert into part1 (value, gender) values ('pterodáctilo', 2);
insert into part1 (value, gender) values ('espécie em extinção', 1);

insert into part2 (value, gender) values ('parecido com o jason', 2);
insert into part2 (value, gender) values ('luminosa', 1);
insert into part2 (value, gender) values ('luminoso', 2);
insert into part2 (value, gender) values ('refutada', 1);
insert into part2 (value, gender) values ('refutado', 2);
insert into part2 (value, gender) values ('globalista', 0);
insert into part2 (value, gender) values ('terraplanista', 0);
insert into part2 (value, gender) values ('sem vírgula', 0);
insert into part2 (value, gender) values ('desmilinguida', 1);
insert into part2 (value, gender) values ('desmilinguido', 2);
insert into part2 (value, gender) values ('dissolvida', 1);
insert into part2 (value, gender) values ('dissolvido', 2);
insert into part2 (value, gender) values ('safada', 1);
insert into part2 (value, gender) values ('safado', 2);
insert into part2 (value, gender) values ('esfacelada', 1);
insert into part2 (value, gender) values ('esfacelado', 2);
insert into part2 (value, gender) values ('sem sal', 0);
insert into part2 (value, gender) values ('espongiforme', 0);
insert into part2 (value, gender) values ('estranha', 1);
insert into part2 (value, gender) values ('estranho', 2);
insert into part2 (value, gender) values ('cabeluda', 1);
insert into part2 (value, gender) values ('cabeludo', 2);
insert into part2 (value, gender) values ('de salto alto', 0);
insert into part2 (value, gender) values ('travestida de barbie', 1);
insert into part2 (value, gender) values ('travestido de urso', 2);
insert into part2 (value, gender) values ('dura', 1);
insert into part2 (value, gender) values ('duro', 2);
insert into part2 (value, gender) values ('mal feita', 1);
insert into part2 (value, gender) values ('mal feito', 2);
insert into part2 (value, gender) values ('panificada', 1);
insert into part2 (value, gender) values ('panificado', 2);
insert into part2 (value, gender) values ('ensaboada', 1);
insert into part2 (value, gender) values ('ensaboado', 2);
insert into part2 (value, gender) values ('barroca', 1);
insert into part2 (value, gender) values ('barroco', 2);
insert into part2 (value, gender) values ('assombrada', 1);
insert into part2 (value, gender) values ('assombrado', 2);
insert into part2 (value, gender) values ('surfista', 0);
insert into part2 (value, gender) values ('programador de php', 2);
insert into part2 (value, gender) values ('programadora de php', 2);
insert into part2 (value, gender) values ('desajustada', 1);
insert into part2 (value, gender) values ('desajustado', 2);
insert into part2 (value, gender) values ('saltitante', 0);
insert into part2 (value, gender) values ('grávida', 1);
insert into part2 (value, gender) values ('grávido', 2);
insert into part2 (value, gender) values ('de abobrinha', 0);
insert into part2 (value, gender) values ('de chuchu', 0);
insert into part2 (value, gender) values ('desqualificada', 1);
insert into part2 (value, gender) values ('desqualificado', 2);
insert into part2 (value, gender) values ('tarada', 1);
insert into part2 (value, gender) values ('tarado', 2);
insert into part2 (value, gender) values ('engasgada', 1);
insert into part2 (value, gender) values ('engasgado', 2);
insert into part2 (value, gender) values ('pole dancer', 0);
insert into part2 (value, gender) values ('desnorteada', 1);
insert into part2 (value, gender) values ('desnorteado', 2);
insert into part2 (value, gender) values ('passeando de crocs', 0);
insert into part2 (value, gender) values ('que desfila de crocs', 0);
insert into part2 (value, gender) values ('desfilando', 0);
insert into part2 (value, gender) values ('profunda', 1);
insert into part2 (value, gender) values ('profundo', 2);
insert into part2 (value, gender) values ('veiuda', 1);
insert into part2 (value, gender) values ('veiudo', 2);
insert into part2 (value, gender) values ('velha', 1);
insert into part2 (value, gender) values ('velho', 2);
insert into part2 (value, gender) values ('com gosto de peixe', 0);
insert into part2 (value, gender) values ('envelhecida', 1);
insert into part2 (value, gender) values ('envelhecido', 2);
insert into part2 (value, gender) values ('cachaceira', 1);
insert into part2 (value, gender) values ('cachaceiro', 2);
insert into part2 (value, gender) values ('bombada', 1);
insert into part2 (value, gender) values ('bombado', 2);
insert into part2 (value, gender) values ('de nadadeiras', 0);
insert into part2 (value, gender) values ('antagonista', 0);
insert into part2 (value, gender) values ('maníaca', 1);
insert into part2 (value, gender) values ('maníaco', 2);
insert into part2 (value, gender) values ('sedentária', 1);
insert into part2 (value, gender) values ('sedentário', 2);
insert into part2 (value, gender) values ('absolutamente', 0);
insert into part2 (value, gender) values ('oriunda do mar', 1);
insert into part2 (value, gender) values ('vindo do mar', 2);
insert into part2 (value, gender) values ('palpiteira', 1);
insert into part2 (value, gender) values ('palpiteiro', 2);
insert into part2 (value, gender) values ('ensanguentada', 1);
insert into part2 (value, gender) values ('ensanguentado', 2);
insert into part2 (value, gender) values ('maluca', 1);
insert into part2 (value, gender) values ('maluco', 2);
insert into part2 (value, gender) values ('com chapéu de alumínio', 0);
insert into part2 (value, gender) values ('folclórica', 1);
insert into part2 (value, gender) values ('folclórico', 2);
insert into part2 (value, gender) values ('alegórica', 1);
insert into part2 (value, gender) values ('alegórico', 2);
insert into part2 (value, gender) values ('hipocondríaca', 1);
insert into part2 (value, gender) values ('hipocondríaco', 2);
insert into part2 (value, gender) values ('figurante', 0);
insert into part2 (value, gender) values ('terrorista', 0);

insert into part3 (value, gender) values ('da calça quadrada', 0);
insert into part3 (value, gender) values ('parecendo uma amoeba', 0);
insert into part3 (value, gender) values ('amolecida', 1);
insert into part3 (value, gender) values ('amolecido', 2);
insert into part3 (value, gender) values ('global', 0);
insert into part3 (value, gender) values ('no ácido sulfúrico', 0);
insert into part3 (value, gender) values ('suspensa no ar', 1);
insert into part3 (value, gender) values ('suspenso no ar', 2);
insert into part3 (value, gender) values ('mastigada por um urso', 1);
insert into part3 (value, gender) values ('mastigado por uma ursinha', 2);
insert into part3 (value, gender) values ('pifada', 1);
insert into part3 (value, gender) values ('pifado', 2);
insert into part3 (value, gender) values ('sem tempero', 0);
insert into part3 (value, gender) values ('destemperada', 1);
insert into part3 (value, gender) values ('destemperado', 2);
insert into part3 (value, gender) values ('descabelada', 1);
insert into part3 (value, gender) values ('descabelado', 2);
insert into part3 (value, gender) values ('e malformada', 1);
insert into part3 (value, gender) values ('e malformado', 2);
insert into part3 (value, gender) values ('mal criada', 1);
insert into part3 (value, gender) values ('mal criado', 2);
insert into part3 (value, gender) values ('com cara de acidente de trem', 0);
insert into part3 (value, gender) values ('que parece a samara', 0);
insert into part3 (value, gender) values ('cancelada pela globo', 1);
insert into part3 (value, gender) values ('cancelado pelo sbt', 2);
insert into part3 (value, gender) values ('tendendo ao infinito', 0);
insert into part3 (value, gender) values ('da casca assombrosa', 1);
insert into part3 (value, gender) values ('do casco assombroso', 2);
insert into part3 (value, gender) values ('sem casaco', 0);
insert into part3 (value, gender) values ('com cara de silverfish', 0);
insert into part3 (value, gender) values ('sem bunda', 0);
insert into part3 (value, gender) values ('no mastro', 0);
insert into part3 (value, gender) values ('num objeto fálico', 0);
insert into part3 (value, gender) values ('sem calcinha', 0);
insert into part3 (value, gender) values ('de calcinha', 0);
insert into part3 (value, gender) values ('que xinga muito no twitter', 0);
insert into part3 (value, gender) values ('no desfiladeiro', 0);
insert into part3 (value, gender) values ('na beira do abismo', 0);
insert into part3 (value, gender) values ('da beira do abismo', 0);
insert into part3 (value, gender) values ('no penhasco', 0);
insert into part3 (value, gender) values ('mucha', 1);
insert into part3 (value, gender) values ('mucho', 2);
insert into part3 (value, gender) values ('podre', 0);
insert into part3 (value, gender) values ('fedida', 1);
insert into part3 (value, gender) values ('fedido', 2);
insert into part3 (value, gender) values ('no carvalho', 0);
insert into part3 (value, gender) values ('no barril', 0);
insert into part3 (value, gender) values ('apreciadora de paratudo', 1);
insert into part3 (value, gender) values ('degustador de paratudo', 2);
insert into part3 (value, gender) values ('sem cérebro', 0);
insert into part3 (value, gender) values ('acéfala', 1);
insert into part3 (value, gender) values ('acéfalo', 2);
insert into part3 (value, gender) values ('no lixo', 0);
insert into part3 (value, gender) values ('onomatopeica', 1);
insert into part3 (value, gender) values ('onomatopeico', 2);
insert into part3 (value, gender) values ('deserdada pela rainha', 1);
insert into part3 (value, gender) values ('deserdado pela rainha', 2);
insert into part3 (value, gender) values ('pra cacete', 0);
insert into part3 (value, gender) values ('para um caralho', 0);
insert into part3 (value, gender) values ('num navio cargueiro', 0);
insert into part3 (value, gender) values ('desfigurada', 1);
insert into part3 (value, gender) values ('desfigurado', 2);
insert into part3 (value, gender) values ('numa sexta feira 13', 0);
insert into part3 (value, gender) values ('esmagada por um titã anômalo', 1);
insert into part3 (value, gender) values ('esmagado por um titã bestial', 2);
insert into part3 (value, gender) values ('que parece que já morreu', 0);
insert into part3 (value, gender) values ('fingindo de morta', 1);
insert into part3 (value, gender) values ('com cara de morto', 2);
insert into part3 (value, gender) values ('conspiracionista', 0);
insert into part3 (value, gender) values ('de perna aberta', 0);
insert into part3 (value, gender) values ('sem perna', 0);
insert into part3 (value, gender) values ('em cima do muro', 0);
insert into part3 (value, gender) values ('da novela das 8', 0);
insert into part3 (value, gender) values ('de novela mexicana', 0);
insert into part3 (value, gender) values ('de dorama coreano', 0);
insert into part3 (value, gender) values ('depois da explosão', 0);
insert into part3 (value, gender) values ('do braço curto', 0);
insert into part3 (value, gender) values ('louca de pó', 1);
insert into part3 (value, gender) values ('virado no pó', 2);
insert into part3 (value, gender) values ('maconheira', 1);
insert into part3 (value, gender) values ('maconheiro', 2);

-- 2021-02-10
insert into part1 (value, gender) values ('criptomoeda', 1);
insert into part1 (value, gender) values ('panda', 0);
insert into part1 (value, gender) values ('saco', 2);
insert into part1 (value, gender) values ('espermatozoide', 2);
insert into part1 (value, gender) values ('membrana', 1);
insert into part1 (value, gender) values ('bagaça', 1);
insert into part1 (value, gender) values ('bagaço', 2);
insert into part1 (value, gender) values ('chá de cogumelo', 2);
insert into part1 (value, gender) values ('cogumelo', 2);
insert into part1 (value, gender) values ('ratoeira', 1);
insert into part1 (value, gender) values ('erro http', 2);
insert into part1 (value, gender) values ('filme de terror', 2);
insert into part1 (value, gender) values ('boquinha', 1);
insert into part1 (value, gender) values ('bocuda', 1);
insert into part1 (value, gender) values ('bocudo', 2);
insert into part1 (value, gender) values ('exorcismo', 2);
insert into part1 (value, gender) values ('caracol', 2);
insert into part1 (value, gender) values ('elefante', 2);
insert into part1 (value, gender) values ('monge', 2);
insert into part1 (value, gender) values ('boneca', 1);
insert into part1 (value, gender) values ('boneco', 2);
insert into part1 (value, gender) values ('bárbaro', 2);
insert into part1 (value, gender) values ('bolinho de arroz', 2);
insert into part1 (value, gender) values ('micróbio', 2);
insert into part1 (value, gender) values ('verme', 2);

insert into part2 (value, gender) values ('na brisa', 0);
insert into part2 (value, gender) values ('atômica', 1);
insert into part2 (value, gender) values ('crosfiteira', 1);
insert into part2 (value, gender) values ('crosfiteiro', 2);
insert into part2 (value, gender) values ('atômico', 2);
insert into part2 (value, gender) values ('sem neurônio', 0);
insert into part2 (value, gender) values ('comedora de bamboo', 1);
insert into part2 (value, gender) values ('comedor de bamboo', 2);
insert into part2 (value, gender) values ('linguaruda', 1);
insert into part2 (value, gender) values ('linguarudo', 2);
insert into part2 (value, gender) values ('despedaçada', 1);
insert into part2 (value, gender) values ('despedaçado', 2);
insert into part2 (value, gender) values ('sem máscara', 0);
insert into part2 (value, gender) values ('desmascarada', 1);
insert into part2 (value, gender) values ('desmascarado', 2);
insert into part2 (value, gender) values ('rabuda', 1);
insert into part2 (value, gender) values ('rabudo', 2);
insert into part2 (value, gender) values ('infantilizada', 1);
insert into part2 (value, gender) values ('infantilizado', 2);
insert into part2 (value, gender) values ('desmembrada', 1);
insert into part2 (value, gender) values ('desmembrado', 2);
insert into part2 (value, gender) values ('liquidificada', 1);
insert into part2 (value, gender) values ('liquidificado', 2);
insert into part2 (value, gender) values ('necromante', 0);
insert into part2 (value, gender) values ('arrombada', 1);
insert into part2 (value, gender) values ('parecida com a Xena', 1);
insert into part2 (value, gender) values ('parecido com a Xena', 2);
insert into part2 (value, gender) values ('maldita', 1);
insert into part2 (value, gender) values ('maldito', 2);
insert into part2 (value, gender) values ('peituda', 1);
insert into part2 (value, gender) values ('espinhuda', 1);
insert into part2 (value, gender) values ('espinhudo', 2);
insert into part2 (value, gender) values ('possuída', 1);
insert into part2 (value, gender) values ('possuído', 2);
insert into part2 (value, gender) values ('feia', 1);
insert into part2 (value, gender) values ('feio', 2);
insert into part2 (value, gender) values ('de chapéu', 0);
insert into part2 (value, gender) values ('branca', 1);
insert into part2 (value, gender) values ('branco', 2);
insert into part2 (value, gender) values ('tibetana', 1);
insert into part2 (value, gender) values ('tibetano', 2);
insert into part2 (value, gender) values ('hentai', 0);

insert into part3 (value, gender) values ('cruzada com o capeta', 1);
insert into part3 (value, gender) values ('cruzado com o capeta', 2);
insert into part3 (value, gender) values ('cor de burro quando foge', 0);
insert into part3 (value, gender) values ('repetente', 0);
insert into part3 (value, gender) values ('na turma do fundão', 0);
insert into part3 (value, gender) values ('que só chega em último lugar', 0);
insert into part3 (value, gender) values ('lambida', 1);
insert into part3 (value, gender) values ('lambido', 2);
insert into part3 (value, gender) values ('verde', 0);
insert into part3 (value, gender) values ('monocromática', 1);
insert into part3 (value, gender) values ('monocromático', 2);
insert into part3 (value, gender) values ('brisada', 0);
insert into part3 (value, gender) values ('investidora de ethereum', 1);
insert into part3 (value, gender) values ('investidor de bitcoin', 2);
insert into part3 (value, gender) values ('do pé torto', 0);
insert into part3 (value, gender) values ('da canela ralada', 0);
insert into part3 (value, gender) values ('extramemente desafinada', 1);
insert into part3 (value, gender) values ('extramemente desafinado', 2);
insert into part3 (value, gender) values ('descendo pelo ralo', 0);
insert into part3 (value, gender) values ('descendo ralo abaixo', 0);
insert into part3 (value, gender) values ('aspirante a princesa guerreira', 0);
insert into part3 (value, gender) values ('que só dá 404', 0);
insert into part3 (value, gender) values ('lactante', 0);
insert into part3 (value, gender) values ('salivante', 0);
insert into part3 (value, gender) values ('que só resmunga', 0);
insert into part3 (value, gender) values ('falida', 1);
insert into part3 (value, gender) values ('falido', 2);
insert into part3 (value, gender) values ('que só sabe tirar onda', 0);
insert into part3 (value, gender) values ('do himalaia', 0);
insert into part3 (value, gender) values ('ondulada', 1);
insert into part3 (value, gender) values ('ondulado', 2);
insert into part3 (value, gender) values ('atropelada', 1);
insert into part3 (value, gender) values ('atropelado', 2);
insert into part3 (value, gender) values ('dubladora de anime', 1);
insert into part3 (value, gender) values ('dublador de anime', 2);
insert into part3 (value, gender) values ('fingindo orgasmo', 0);

-- 2021-02-11
insert into part1 (value, gender) values ('piriguete', 1);
insert into part1 (value, gender) values ('cavala', 1);
insert into part1 (value, gender) values ('cavalo', 2);
insert into part1 (value, gender) values ('cavalinha', 1);
insert into part1 (value, gender) values ('cavalinho', 2);
insert into part1 (value, gender) values ('sua jumenta', 1);
insert into part1 (value, gender) values ('seu jumento', 2);
insert into part1 (value, gender) values ('filha duma égua', 1);
insert into part1 (value, gender) values ('filho duma égua', 2);
insert into part1 (value, gender) values ('sua eguinha', 1);
insert into part1 (value, gender) values ('minha eguinha', 1);
insert into part1 (value, gender) values ('pudim', 2);
insert into part1 (value, gender) values ('seu pau', 2);
insert into part1 (value, gender) values ('pão', 2);
insert into part1 (value, gender) values ('morcego', 2);
insert into part1 (value, gender) values ('que morceguinha', 1);
insert into part1 (value, gender) values ('neurônio', 2);
insert into part1 (value, gender) values ('sua bisnaguinha', 1);
insert into part1 (value, gender) values ('seu bis', 1);
insert into part1 (value, gender) values ('galinha', 1);
insert into part1 (value, gender) values ('galo', 2);
insert into part1 (value, gender) values ('filho de uma piranha', 1);
insert into part1 (value, gender) values ('kpopeira', 1);
insert into part1 (value, gender) values ('kpopeiro', 2);
insert into part1 (value, gender) values ('energético', 2);
insert into part1 (value, gender) values ('borra', 1);
insert into part1 (value, gender) values ('camisinha', 1);
insert into part1 (value, gender) values ('achocolatado', 2);
insert into part1 (value, gender) values ('succubus', 1);
insert into part1 (value, gender) values ('incubus', 2);
insert into part1 (value, gender) values ('buraco negro', 2);
insert into part1 (value, gender) values ('sua simulação', 1);
insert into part1 (value, gender) values ('homem bomba', 2);
insert into part1 (value, gender) values ('mulher bomba', 1);

insert into part2 (value, gender) values ('usada', 1);
insert into part2 (value, gender) values ('usado', 2);
insert into part2 (value, gender) values ('iluminada por fótons', 1);
insert into part2 (value, gender) values ('iluminado por fótons', 2);
insert into part2 (value, gender) values ('em pó', 0);
insert into part2 (value, gender) values ('presa na matrix', 1);
insert into part2 (value, gender) values ('preso na matrix', 2);
insert into part2 (value, gender) values ('de autocomplete', 0);
insert into part2 (value, gender) values ('de café', 0);
insert into part2 (value, gender) values ('sugadora de energia', 1);
insert into part2 (value, gender) values ('sugador de energia', 2);
insert into part2 (value, gender) values ('pocotó', 0);
insert into part2 (value, gender) values ('com vodka', 0);
insert into part2 (value, gender) values ('na aguinha', 0);
insert into part2 (value, gender) values ('dropada', 1);
insert into part2 (value, gender) values ('dropado', 2);
insert into part2 (value, gender) values ('dopada', 1);
insert into part2 (value, gender) values ('dopado', 2);
insert into part2 (value, gender) values ('sertaneja', 1);
insert into part2 (value, gender) values ('sertanejo', 2);
insert into part2 (value, gender) values ('ensopada', 1);
insert into part2 (value, gender) values ('ensopado', 2);
insert into part2 (value, gender) values ('na chapa', 0);
insert into part2 (value, gender) values ('latindo', 0);
insert into part2 (value, gender) values ('de férias', 0);
insert into part2 (value, gender) values ('desconstruída', 1);
insert into part2 (value, gender) values ('desconstruído', 2);
insert into part2 (value, gender) values ('desengonçada', 1);
insert into part2 (value, gender) values ('desengonçado', 2);
insert into part2 (value, gender) values ('sem cabeça', 0);
insert into part2 (value, gender) values ('mordida', 1);
insert into part2 (value, gender) values ('mordido', 2);
insert into part2 (value, gender) values ('ensacada', 1);
insert into part2 (value, gender) values ('ensacado', 2);
insert into part2 (value, gender) values ('d`angola', 0);
insert into part2 (value, gender) values ('sem pescoço', 0);
insert into part2 (value, gender) values ('banguela', 0);
insert into part2 (value, gender) values ('gaseificada', 1);
insert into part2 (value, gender) values ('gaseificado', 2);
insert into part2 (value, gender) values ('sem gás', 0);
insert into part2 (value, gender) values ('que roubou meu coração', 0);
insert into part2 (value, gender) values ('desligada', 1);
insert into part2 (value, gender) values ('desligado', 2);
insert into part2 (value, gender) values ('caramelada', 1);
insert into part2 (value, gender) values ('caramelado', 2);
insert into part2 (value, gender) values ('da cara melada', 0);
insert into part2 (value, gender) values ('dissimulada', 1);
insert into part2 (value, gender) values ('dissimulado', 2);
insert into part2 (value, gender) values ('de shortinho', 0);
insert into part2 (value, gender) values ('de saia', 0);

insert into part3 (value, gender) values ('dentro de uma simulação', 0);
insert into part3 (value, gender) values ('parecida com o godzilla', 1);
insert into part3 (value, gender) values ('parecido com o godzilla', 2);
insert into part3 (value, gender) values ('mas não vale nem um centavo', 0);
insert into part3 (value, gender) values ('mas não vale nada', 0);
insert into part3 (value, gender) values ('na escuridão', 0);
insert into part3 (value, gender) values ('bandida', 1);
insert into part3 (value, gender) values ('bandido', 2);
insert into part3 (value, gender) values ('criminosa', 1);
insert into part3 (value, gender) values ('criminoso', 2);
insert into part3 (value, gender) values ('desmiolada', 1);
insert into part3 (value, gender) values ('desmiolado', 2);
insert into part3 (value, gender) values ('descafeinada', 1);
insert into part3 (value, gender) values ('descafeinado', 2);
insert into part3 (value, gender) values ('sem taurina', 0);
insert into part3 (value, gender) values ('sem bolinhas', 0);
insert into part3 (value, gender) values ('sem bola', 0);
insert into part3 (value, gender) values ('sem pai', 0);
insert into part3 (value, gender) values ('encerada', 1);
insert into part3 (value, gender) values ('encerado', 2);
insert into part3 (value, gender) values ('prensada', 1);
insert into part3 (value, gender) values ('prensado', 2);
insert into part3 (value, gender) values ('igual o cachorro do vizinho', 0);
insert into part3 (value, gender) values ('sem legado', 0);
insert into part3 (value, gender) values ('que o diabo amassou', 0);
insert into part3 (value, gender) values ('em conserva', 0);
insert into part3 (value, gender) values ('na laje', 0);
insert into part3 (value, gender) values ('pela metade', 0);
insert into part3 (value, gender) values ('pocotó pocotó', 0);
insert into part3 (value, gender) values ('desnatada', 1);
insert into part3 (value, gender) values ('desnatado', 2);
insert into part3 (value, gender) values ('integral', 0);
insert into part3 (value, gender) values ('de fio dental', 0);
insert into part3 (value, gender) values ('gozada', 1);
insert into part3 (value, gender) values ('gozado', 2);
insert into part3 (value, gender) values ('gozadinha', 1);
insert into part3 (value, gender) values ('gozadinho', 2);
insert into part3 (value, gender) values ('durante a cremação', 0);
insert into part3 (value, gender) values ('no meio da cremação', 0);
insert into part3 (value, gender) values ('em processo de decomposição', 0);
insert into part3 (value, gender) values ('atolada', 1);
insert into part3 (value, gender) values ('atolado', 2);
insert into part3 (value, gender) values ('atoladinha', 1);
insert into part3 (value, gender) values ('atoladinho', 2);

-- 2021-02-12
insert into part1 (value, gender) values ('cérebro de vaca', 2);
insert into part1 (value, gender) values ('analfabeta', 1);
insert into part1 (value, gender) values ('analfabeto', 2);
insert into part1 (value, gender) values ('protozoário', 2);
insert into part1 (value, gender) values ('anis estrelado', 2);
insert into part1 (value, gender) values ('vuvuzela', 1);
insert into part1 (value, gender) values ('unha', 1);
insert into part1 (value, gender) values ('tooltip', 2);
insert into part1 (value, gender) values ('milha', 1);
insert into part1 (value, gender) values ('milho', 2);
insert into part1 (value, gender) values ('broto', 2);
insert into part1 (value, gender) values ('feijoada', 1);
insert into part1 (value, gender) values ('commit', 2);
insert into part1 (value, gender) values ('lactobacilo', 2);
insert into part1 (value, gender) values ('dedada', 1);
insert into part1 (value, gender) values ('porta', 1);

insert into part2 (value, gender) values ('pré histórica', 1);
insert into part2 (value, gender) values ('pré histórico', 2);
insert into part2 (value, gender) values ('do poço', 0);
insert into part2 (value, gender) values ('mal depilada', 1);
insert into part2 (value, gender) values ('mal depilado', 2);
insert into part2 (value, gender) values ('com encefalopatia espongiforme', 0);
insert into part2 (value, gender) values ('funcional', 0);
insert into part2 (value, gender) values ('megalomaníaca', 1);
insert into part2 (value, gender) values ('megalomaníaco', 2);
insert into part2 (value, gender) values ('com cara de', 0);
insert into part2 (value, gender) values ('com a cara', 0);
insert into part2 (value, gender) values ('que parece que tomou uma pintada', 0);
insert into part2 (value, gender) values ('espatifada', 1);
insert into part2 (value, gender) values ('espatifado', 2);
insert into part2 (value, gender) values ('qualhada', 1);
insert into part2 (value, gender) values ('qualhado', 2);
insert into part2 (value, gender) values ('mal pintada', 1);
insert into part2 (value, gender) values ('mal pintado', 2);
insert into part2 (value, gender) values ('escorregadia', 1);
insert into part2 (value, gender) values ('escorregadio', 2);
insert into part2 (value, gender) values ('desalinhada', 1);
insert into part2 (value, gender) values ('desalinhado', 2);
insert into part2 (value, gender) values ('lunática', 1);
insert into part2 (value, gender) values ('lunático', 2);
insert into part2 (value, gender) values ('náutica', 1);
insert into part2 (value, gender) values ('náutico', 2);
insert into part2 (value, gender) values ('de feijão', 2);
insert into part2 (value, gender) values ('viva', 1);
insert into part2 (value, gender) values ('vivo', 2);
insert into part2 (value, gender) values ('sem sinal', 0);
insert into part2 (value, gender) values ('salafrária', 1);
insert into part2 (value, gender) values ('salafrário', 2);
insert into part2 (value, gender) values ('do deserto', 0);
insert into part2 (value, gender) values ('com parkinson', 0);
insert into part2 (value, gender) values ('jurássica', 1);
insert into part2 (value, gender) values ('jurássico', 2);
insert into part2 (value, gender) values ('burra', 1);
insert into part2 (value, gender) values ('burro', 2);

insert into part3 (value, gender) values ('da turma do fundão', 0);
insert into part3 (value, gender) values ('da cara pintada', 0);
insert into part3 (value, gender) values ('na cara', 0);
insert into part3 (value, gender) values ('e borrada', 1);
insert into part3 (value, gender) values ('e borrado', 2);
insert into part3 (value, gender) values ('no chão', 0);
insert into part3 (value, gender) values ('desdentada', 1);
insert into part3 (value, gender) values ('desdentado', 2);
insert into part3 (value, gender) values ('azeda', 1);
insert into part3 (value, gender) values ('azedo', 2);
insert into part3 (value, gender) values ('mofada', 1);
insert into part3 (value, gender) values ('mofado', 2);
insert into part3 (value, gender) values ('envenenada', 1);
insert into part3 (value, gender) values ('envenenado', 2);
insert into part3 (value, gender) values ('que só enche o saco', 0);
insert into part3 (value, gender) values ('com a lerdeza de um slowpoke', 0);
insert into part3 (value, gender) values ('sem revisão', 0);
insert into part3 (value, gender) values ('pendente de revisão', 0);
insert into part3 (value, gender) values ('na vida', 0);
insert into part3 (value, gender) values ('sem vida', 0);
insert into part3 (value, gender) values ('da tim', 0);
insert into part3 (value, gender) values ('mesmo', 0);
insert into part3 (value, gender) values ('paga pau', 0);
insert into part3 (value, gender) values ('feito uma porta', 0);
insert into part3 (value, gender) values ('grossa', 1);
insert into part3 (value, gender) values ('grosso', 2);

-- 2021-02-20
insert into part1 (value, gender) values ('traíra', 1);
insert into part1 (value, gender) values ('arraia', 1);
insert into part1 (value, gender) values ('otome', 1);
insert into part1 (value, gender) values ('otaku', 2);

insert into part2 (value, gender) values ('gigante', 0);
insert into part2 (value, gender) values ('imatura', 1);
insert into part2 (value, gender) values ('imaturo', 2);
insert into part2 (value, gender) values ('encravada', 1);
insert into part2 (value, gender) values ('encravado', 2);
insert into part2 (value, gender) values ('mal desenvolvida', 1);
insert into part2 (value, gender) values ('mal desenvolvido', 2);
insert into part2 (value, gender) values ('duvidosa', 1);
insert into part2 (value, gender) values ('duvidoso', 2);

insert into part3 (value, gender) values ('x9', 0);
insert into part3 (value, gender) values ('emputecida', 1);
insert into part3 (value, gender) values ('emputecido', 2);
insert into part3 (value, gender) values ('totalmente nada a ver', 0);
insert into part3 (value, gender) values ('chapada', 1);
insert into part3 (value, gender) values ('chapado', 2);
insert into part3 (value, gender) values ('meramente ilustrativa', 1);
insert into part3 (value, gender) values ('meramente ilustrativo', 2);
insert into part3 (value, gender) values ('nada didática', 1);
insert into part3 (value, gender) values ('nada didático', 2);

-- 2021-02-21
